### ISSUE TITLE
add `--output json` to `workloads list` command

### ISSUE THREAD

**Issue by mingxiao** [vmware-tanzu/apps-cli-plugin#12]
### Description of problem

I'd like to get a list of workloads in json format for scripting and programmatic parsing.

### Proposed solution

```gherkin
Given I do `tanzu apps workload list --output json`
Then I see output of current information in json format
```

**Comment by heyjcollins** [comment]
### Acceptance
1. validated `tanzu apps workload list -o yaml/json` returns yaml/json format
2. confirmed yaml and json output are syntactically valid
3. logged separate issue for supporting `... -o yml` as well (for workload get and list)
