### ISSUE TITLE
Update the help text for some flags to be consistent with other attributes

### ISSUE THREAD

**Issue by atmandhol** [vmware-tanzu/apps-cli-plugin#120]
### Please fill out the issue checklist below and provide ALL the requested information.

- [x] I reviewed open and closed Github issues that may be related to my problem.
- [x] I am reporting a bug that others will be able to reproduce.

### Describe the bug
Update the help text for some flags to use the parenthesis for usage info.

### Expected behavior
```
--sub-path path    relative path inside the repo or image to treat as application root (to unset, pass empty string "")
--live-update      put the workload in live update mode (--live-update=false to disable)
--debug            put the workload in debug mode (--debug=false to disable)
```

**Comment by heyjcollins** [comment]
### AC
confimed help changes in `create`, `update` and `apply`

Thanks @warango4 !
