### ISSUE TITLE
`workload create` on Windows throws "x509: certificate signed by unknown authority"

### ISSUE THREAD

**Issue by atwoosnam** [vmware-tanzu/apps-cli-plugin#127]
### Please fill out the issue checklist below and provide ALL the requested information.

- [x] I reviewed open and closed Github issues that may be related to my problem.
- [x] I am reporting a bug that others will be able to reproduce.

### Describe the bug
When I invoke `tanzu apps workload apply` or `tanzu apps workload create` on Windows, the command fails with exit status 1 & error:

> Writing 'index.docker.io/atwoosnam/sample-app:latest': Writing image: Retried 5 times: Get "https://index.docker.io/v2/": x509: certificate signed by unknown authority

### Expected behavior

1. No error 
2. App image gets written to the repository provided as the `--source-image` parameter

### Steps to Reproduce

1. Using a Windows OS...
3. Install tanzu cli + apps plugin
4. Clone [sample java accelerator app](https://github.com/sample-accelerators/tanzu-java-web-app) & cd into repo
5. Try to push app to TAP via `tanzu apps workload apply -f config/workload.yaml --live-update --local-path {PATH_TO_JAVA_ACCELERATOR_REPO} --source-image {YOUR_IMAGE_REPOSITORY} --namespace {YOUR_TAP_NAMESPACE} --yes`
6. Notice "`Error: Writing '{IMAGE}': Writing image: Retried 5 times: Get "https://{IMAGE_REPO_DOMAIN}/v2/": x509: certificate signed by unknown authority`"

### Screenshots
![image](https://user-images.githubusercontent.com/22666145/169602630-2a754100-e6f2-49e4-b170-2badc4a07b9b.png)
![image](https://user-images.githubusercontent.com/22666145/169572664-eb388035-e12e-41db-bb5c-cfe768f8147b.png)

### Version (Apps plugin version, Version of K8s running on cluster)
Put the output of the following commad
```sh
tanzu version && tanzu apps version
``` 
```
version: v0.11.6
buildDate: 2022-05-18
sha: 6819c5a1
v0.5.1
```
### Environment where the bug was observed (cloud, OS, etc)
Windows 11 Enterprise, Version 21H2 (OS build 22000.675)

### Additional context & Relevant Debug Output (Logs, etc)

- I've tried changing these things without seeing the error change:
  - URL provided for `--source-image`:
    - `harbor.dhaka.cf-app.com/awoosnam`
    - `hub.docker.com/repository/docker/atwoosnam/sample-app`
    - `hub.docker.com/atwoosnam/sample-app`
    - `index.docker.io/atwoosnam/sample-app`
    - `docker.io/atwoosnam/sample-app`
    - `docker.io/rkamaldocker/sample-app`
  - different `tanzu app` commands
    - `workload create` and `workload apply` both give the same error
  - different shells in Windows:
    - Powershell (as administrator)
    - Git Bash ([info](https://appuals.com/what-is-git-bash/))
- I **am** able to push to my `atwoosnam/sample-app` image repository in DockerHub using the Docker CLI
![image](https://user-images.githubusercontent.com/22666145/169603047-ea855f42-b6e8-407e-b735-39b24e2d29ba.png)
- My teammate @zzori-theoriginal got the same error when invoking `tanzu plugin list` on windows:
![image](https://user-images.githubusercontent.com/22666145/169603292-0b89a25f-e902-4fd5-8114-e4b659f7e2cb.png)

**Comment by atmandhol** [comment]
Hello @atwoosnam , Thank you for raising this issue, and appreciate the level of details provided in the description. There is a known issue with imgpkg versions 0.19.0 and below. See https://carvel.dev/imgpkg/docs/v0.29.0/ca-certs-windows/. We will upgrade the version of imgpkg used in the Apps plugin (currently 0.17.0) which should mitigate this issue.

**Comment by cmoulliard** [comment]
FYI: This is not an issue specific to the Window's user as it also occurs when we push an image from local source project to a private images registry on a mac machine.

So we need somme additional parameters for the `tanzu apps workload create/apply` command as we have with `imgpkg push` command to disable the TLS verification (or to pass he CA cert)
```
imgpkg push --registry-verify-certs='False' ....
```

Error that I got on my mac machine

```
tanzu apps workload apply -f config/workload.yaml --local-path . --source-image registry.harbor.10.0.77.176.nip.io:32443/demo/tanzu-java-web-app-source -n demo-1
? Publish source in "." to "registry.harbor.10.0.77.176.nip.io:32443/demo/tanzu-java-web-app-source"? It may be visible to others who can pull images from that repository Yes
Publishing source in "." to "registry.harbor.10.0.77.176.nip.io:32443/demo/tanzu-java-web-app-source"...
Error: Writing 'registry.harbor.10.0.77.176.nip.io:32443/demo/tanzu-java-web-app-source:latest': Writing image: Retried 5 times: Get "https://registry.harbor.10.0.77.176.nip.io:32443/v2/": x509: certificate signed by unknown authority
Error: exit status 1

```

**Comment by atmandhol** [comment]
@cmoulliard Discussion related to supporting additional flags like the `ca-cert` is done in the following issue:
https://github.com/vmware-tanzu/apps-cli-plugin/issues/116
