### ISSUE TITLE
Update help output for `--service-ref` flag in create/update/apply

### ISSUE THREAD

**Issue by heyjcollins** [vmware-tanzu/apps-cli-plugin#128]
### Description of problem
current help doesn't describe the different sections of the service-ref object that need to be provided as the flag value.
It provides a specific example. It's unclear to end-users and should be improved.

### Proposed solution

Update the help output for the `--service-ref` flag in `workload create/update/apply`

**Current output:**
```
--service-ref object reference   object reference for a service to bind to the workload "database=rabbitmq.com/v1beta1:RabbitmqCluster:my-broker" ("database-" to remove, flag can be used multiple times)
```

**Replacement output:**
@danfein - need copy

**Comment by warango4** [comment]
As per discussion, output should look like:

```md
--service-ref   object reference for a service to bind to the workload "service-ref-name=apiVersion:kind:service-binding-name" ("service-ref-name-" to remove, flag can be used multiple times)
```
