### ISSUE TITLE
.tanzuignore supports regex -- placeholder

### ISSUE THREAD

**Issue by heyjcollins** [vmware-tanzu/apps-cli-plugin#132]
### Description of problem

Extend the work done in #33 to support regex.

PM to complete 

### Proposed solution

<Please describe your proposed solution, preferably in the following style:>

```gherkin
Given <Some Condition>
When <Something Happens>
Then <This other thing should happen?>
```

### Example

<Code snippets that illustrate the when/then blocks>

**Comment by scothis** [comment]
Please don't define a new syntax for the `.tanzuignore` file, use the existing syntax that is common with `.gitignore`, `.dockerignore` etc. If a user has an existing ignore file that is appropriate, they could use that file by `--ignore-file .dockerignore` while the default value for `--ignore-file` would be `.tanzuignore`

**Comment by heyjcollins** [comment]
Going to close this issue as we haven't received any votes or feedback requesting this feature be added.
Feel free to repopen with comment if this is an enhancement you're interested in.
