### ISSUE TITLE
Append "next command recommendations" to the output from `workload create/update/apply/get`

### ISSUE THREAD

**Issue by heyjcollins** [vmware-tanzu/apps-cli-plugin#150]
### Description of problem
App devs experiencing issues with their workload (e.g. not making it through a supply chain) get stuck while troubleshooting and don't readily/easily discover the `tail` command and as a result quickly learn to use other tools while troubleshooting.

We can address this problem incrementally, and a quick/easy way to begin doing so it to recommend certain commands that would logically be executed next in the output.

### Proposed solution

1. Append a recommendation to run `tanzu apps workload tail YOUR-APP` to the current output for `workload create/update/apply AND get`
2. Append a recommendation to run `tanzu apps workload get YOUR-APP` to the current output for `workload create/update/apply`

### Example
**tanzu apps workload create/update/apply**
```
%tanzu apps workload create/update/apply my-app --local-path ~/workspace/tanzu-java-web-app --type web --source-image gcr.io/pivotal-knative/jc-apps
? Publish source in "/Users/collinsjo/workspace/tanzu-java-web-app" to "gcr.io/pivotal-knative/jc-apps"? It may be visible to others who can pull images from that repository Yes
Publishing source in "/Users/collinsjo/workspace/tanzu-java-web-app" to "gcr.io/pivotal-knative/jc-apps"...
Published source
Create workload:
      1 + |---
      2 + |apiVersion: carto.run/v1alpha1
      3 + |kind: Workload
      4 + |metadata:
      5 + |  labels:
      6 + |    apps.tanzu.vmware.com/workload-type: web
      7 + |  name: my-app
      8 + |  namespace: ns1
      9 + |spec:
     10 + |  source:
     11 + |    image: gcr.io/pivotal-knative/jc-apps:latest@sha256:22f23f4f143ce371fbce513601423f7965ff070572882c200a3191374f4daf56

? Do you want to create this workload? Yes
Created workload "my-app"

Tail workload logs by running "tanzu apps workload tail my-app --since 120m" (adjust "--since" value as needed)
View a snapshot of the workload state by running "tanzu apps workload get my-app"

%|
```

**tanzu apps workload get**
```
%tanzu apps workload get my-app
# my-app: Unknown
---
Source
type:    source image
image:   gcr.io/pivotal-knative/jc-apps:latest@sha256:22f23f4f143ce371fbce513601423f7965ff070572882c200a3191374f4daf56

Supply Chain
name:          source-to-url
last update:   6m32s
ready:         Unknown

RESOURCE          READY   TIME
source-provider
deliverable
image-builder
config-provider
app-config
config-writer

Issues
reason:    MissingValueAtPath
message:   waiting to read value [.status.latestImage] from resource [image.kpack.io/my-app] in namespace [ns1]

Pods
NAME                       STATUS   RESTARTS   AGE
my-app-build-1-build-pod   Failed   0          6m31s

Tail workload logs by running "tanzu apps workload tail my-app --since 120m" (adjust "--since" value as needed)

%|
```

### Additional context
cc @danfein - please review and make any UX suggestions/alterations

**Comment by atmandhol** [comment]
**suggestion**: if the issues section is something other than "No issues reported.", we should show the tail command recommendation right below the issues section and before pods. Otherwise, if there are no issues, we should not show the tail command info

**Comment by atmandhol** [comment]
**suggestion**: We should add namespace `-n namespace` to the INFO hint

**Comment by danfein** [comment]
The original workload get mockups used 

```
To check workload status use 'tanzu workload get NAME --namespace NAME'.
```

Given that we may want to show more than one messege we could probably shorten them a bit.

```
Get workload logs with ‘tanzu apps workload tail <name>’
Get workload status with ‘tanzu apps workload get <name>’
```

Where <name> is populated by the name of the workload that triggered the command, to make the suggestion contextually clear, and so the user can copy-paste the suggestion as-is.

I would like to skip the --namespace if possible, just because it isn't always required, and shorter commands are nice.

Would it be reasonable to have some kind of logic that checks the namespace of the workload, and if it is not default we add in (and populate) the namespace flag?

```
Get workload status with ‘tanzu apps workload get <name> --namespace <ns-name>'
```

ex

```
Get workload status with `tanzu apps workload get pet-clinic-df --namespace df-test`
```

RE @atmandhol 's suggestion to show/hide tail depending on presence of issues, no strong feelings, but there may be reasons to check logs besides issues, so it wouldn't hurt to include it in both cases. 

If these messages are the first of many (and this is a good pattern for hinting/communicating) it is worth considering when we might hide them, just so we don't blow folks up with notices.

**Comment by danfein** [comment]
I kind of like the suggestive  tone of 'to check X use Y' more than the imparative 'get x with y', it is a little longer. 

Could avoid thinking about voice/tone AND go even shorter with something like 
```
To see logs:    ‘tanzu apps workload tail <name>’
To get status:  ‘tanzu apps workload get <name>’
```

Thoughts?

**Comment by heyjcollins** [comment]
Let's go with the final recco above.

**Comment by warango4** [comment]
From conversation with design:

- If workload is running in other than `default` namespace, `--namespace` and its name will be used in the help message.

```go
To see logs:    "tanzu apps workload tail <name> --namespace <namespace>"
To get status:  "tanzu apps workload get <name> --namespace <namespace>"
```

- Will use double quotes insted of single quote or backtick

- Message in `workload get` will be put at the end of the command output, `tail` does not necessary has to be for troubleshooting, they may want to check logs even if the workload is in a `Ready` status.
