### ISSUE TITLE
`cluster-supply-chain get` is recommended from `cluster-supply-chain list`

### ISSUE THREAD

**Issue by heyjcollins** [vmware-tanzu/apps-cli-plugin#158]
### Description of problem

this is a fast-follow tweak to this original issue: https://github.com/vmware-tanzu/apps-cli-plugin/issues/151 

the recommended command conent should be updated as per discussions to:

```
To view details:  ‘tanzu apps cluster-supply-chain get <name>’
```

**Comment by warango4** [comment]
From conversation with design and as mentioned in #150
- Will use double quotes insted of single quote or backtick
