### ISSUE TITLE
Add support for Windows test in e2e test suite 

### ISSUE THREAD

**Issue by shashwathi** [vmware-tanzu/apps-cli-plugin#160]
### Description of problem

Currently CI does not support Installing and testing Apps plugin functionality on Windows OS. This story is about adding support for that feature.

### Actions:
- Add a Windows OS runner in Github Actions CI
- Add Installation tests in Windows OS
- Run Integration test suite on Windows OS

**Comment by shaheerkootteeri** [comment]
Integration test on windows OS runner is not implemented as part of the PR
