### ISSUE TITLE
Provide windows release in zip file instead of tar.gz

### ISSUE THREAD

**Issue by odinnordico** [vmware-tanzu/apps-cli-plugin#167]
### Description of problem

Windows users must install additional tools to uncompress the release provided artifact because it is packaged in `tar.gz` providing it in `zip` format would be easier for users and more standard.

### Proposed solution

Package windows artifact in `zip` format

```gherkin
Given The apps cli plugin
When a release/pre-release is cut
Then the published windows artifact is in zip format
```

### Example

<Code snippets that illustrate the when/then blocks>

**Comment by scothis** [comment]
My recommendation is to distribute the plugin as an OCI image. This is the recommended distribution mechanism for tangy cli plugins and it will solve your platform specific issues.

See https://github.com/vmware-tanzu/tanzu-framework/blob/main/docs/cli/plugin_implementation_guide.md#plugin-discovery-source

```
 tanzu plugin source add --name admin --type oci --uri projects.registry.vmware.com/tkg/tanzu-plugins/admin-plugins:v0.11.0-dev
 ```
