### ISSUE TITLE
Maven source is supported via command flags (for workload create & apply)

### ISSUE THREAD

**Issue by heyjcollins** [vmware-tanzu/apps-cli-plugin#170]
### Description of problem

It's now possible to support creating a workload with a reference to a maven repo containing the workload code.
The current implementation requires the user to pass in a complex parameter via `--param-yaml` flag.
The ask here is to provide first-class support for maven source via command flags.

#### Flags 
*  **Must-have flags** (non-optional config needed to specify maven artifact)
   validation should fail if not provided
   ```
   --maven-group       string  maven project to pull artifact from
   --maven-artifact    string  name of maven artifact 
   --maven-version     string  version number of maven artifact
   ```
*  **Optional flags** that we can anticipate folks needing
   ```
   --maven-url         string  url of maven repository to pull artifact from
   --maven-secret-name string  name of the k8s secret containing credentials for the maven repository
   --maven-type        string  maven packaging type, defaults to jar 
   ```

#### Error handling for missing maven flags

1. **First choice,** breaks with precedent for missing flags, but is similar to what we use for missing flag values where the message comes before the list of missing things.
   ```
   $ tanzu apps workload create NAME --maven-artifact --type web
   Error: Missing required value: --maven-group, --maven-version
   ```
1. **Second choice,** more consistent with the existing missing flag patterns
   ```
   $ tanzu apps workload create NAME --maven-artifact --type web
   Error: --maven-group, --maven-version: Required value
   ```

Example messages:
missing value message: `Error: flag needs an argument: --wait-timeout`
missing flag message:   `Error: --git-repo: Required value`
missing flag message:   `Error: [--git-branch, --git-tag]: Required value: expected exactly one, got neither`

#### Too much configuration case
* ```
  > tanzu apps workload create NAME 
  /--maven-artifact <value>
  /--maven-version  <value>
  /--maven-group    <value>
  /--params-yaml    <maven config>
  /--type web

  create workload:
      ...<diff>...
  Notice: Maven configuration flags have overwritten values provided by --params-yaml.

  ? Do you want to create this workload? (y/N)
  ```

### Describe alternatives you've considered
* Providing a single maven flag which expects an object which includes all the flag values in expected order
* Supporting specification through a file

### Additional context
We have deliberately omitted a possible `--maven-classifier` flag because although it's part of the spec, the classifier is implemented in Source Controller code, but not tested or used regularly and at this time we don't have a use case within the tanzu context that warrants adding a flag for it. 
We'll consider adding `--maven-classifier` if/when we get signal.
Although this flag won't be implemented, here's the flag name and help output for possible future reference/discoverability:
   ```
   --maven-classifier  string  maven artifact classifier
   ```

**Comment by danfein** [comment]
Must-have flags (non-optional config needed to specify maven artifact)

```
--maven-group       string  maven project to pull artifact from
--maven-artifact    string  name of maven artifact 
--maven-version     string  version number of maven artifact
```

Optional flags that we can anticipate folks needing

```
--maven-url         string  url of maven repository to pull artifact from
--maven-secret-name string  name of saved secret used to authenticate with maven repository
```

In the spec, but less sure about how often/commonly needed

```
--maven-type        string  maven packaging type, defaults to jar 
--maven-classifier  string  maven artifact classifier
```

**Comment by danfein** [comment]
Proposed error handling for missing maven flags

First choice, breaks with precedent for missing flags, but is similar to what we use for missing flag values

```
$ tanzu apps workload create NAME --maven-artifact --type web
Error: Missing required value: --maven-group, --maven-version
```

Second choice, more consistent with the existing missing flag patterns

```
$ tanzu apps workload create NAME --maven-artifact --type web
Error: --maven-group, --maven-version: Required value
```


Example missing value message: `Error: flag needs an argument: --wait-timeout`
Example missing flag message:   `Error: --git-repo: Required value`
Example missing flag message:   `Error: [--git-branch, --git-tag]: Required value: expected exactly one, got neither`

**Comment by danfein** [comment]
Too much configuration case

```
> tanzu apps workload create NAME 
/--maven-artifact <value>
/--maven-version  <value>
/--maven-group    <value>
/--params-yaml    <maven config>
/--type web

create workload:
    <diff>
Notice: Maven configuration flags have overwritten values provided by --params-yaml.

? Do you want to create this workload? (y/N)
```

**Comment by rashedkvm** [comment]
Here are some additional details. Workload `parms` for Maven Artifact

| Param Key | Flag | Decription |
|---|---|---|
| maven_repository_url | `--maven-url` | Repository URL (`https` required, no `http`) |
| maven_repository_secret_name |`--maven-secret-name`| K8s secret name   |
| maven.artifactId | `--maven-artifact` | Artifact ID  |
| maven.version | `--maven-version` |  Artifact Version. Fixed version (x.x.x), Latest version (LATEST), Release version "RELASE", snapshot version (*-SNAPSHOT) |
| maven.groupId |` --maven-group` | Artifact group ID   |
| maven.type | `--maven-type` | Artifact type (jar, war, zip, etc.). Default is jar     |

**Comment by rashedkvm** [comment]
From my discussion with the Supply Chain team 

> neither `maven_repository_url`  nor `maven_repository_secret_name` would be overridable
that's because in the supply chain the parameters there are configured with `value` rather than `default`

@danfein for now should we remove flag `--maven-url ` & `--maven-secret-name`?

**Comment by danfein** [comment]
Lets pull the flags, it sounds like even if we add them to the params that the supply chain wouldn't be expecting/listening for them.

**Comment by heyjcollins** [comment]
from offline discussion with team regarding precedent.
* if >= 1 `--maven*` flag is included in the command incantation and `maven`-related values are also included in `--params-yaml`, the maven-related values should be ignored.

If not all the required `--maven*` flags are provided, the plugin should throw and error indicating which flags are missing.

We discussed the possibility of merging the inputs from `--params-yaml` and `--maven*` and have decided against that approach (the UX may be confusing and the implementation non-trivial relative to simple binary approach we'll proceed with).
