### ISSUE TITLE
Weird behaviour in flag interaction when creating workload from git source

### ISSUE THREAD

**Issue by warango4** [vmware-tanzu/apps-cli-plugin#179]
### Please fill out the issue checklist below and provide ALL the requested information.

- [x] I reviewed open and closed Github issues that may be related to my problem.
- [x] I am reporting a bug that others will be able to reproduce.

### Describe the bug

When creating a workload from git source, it is allowed to set git tag, git branch and git commit. When not setting at least one of those there is a message saying 
```bash
[--git-branch, --git-tag]: Required value: expected exactly one, got neither
```
This can be misleading for user and wouldn't know what's actually the way a workload should be created. 

Also, when updating `commit` field, `tag` field is deleted. Same if updating `tag`, then `commit` would be deleted

*WHEN UPDATING COMMIT*
<img width="1253" alt="image" src="https://user-images.githubusercontent.com/22118549/173860434-43e93130-d349-4256-b79d-1af1bf9e2fee.png">

<img width="1257" alt="image" src="https://user-images.githubusercontent.com/22118549/173860949-5eeb952c-7f41-4628-85c2-a6082052493a.png">

*WHEN UPDATING TAG*
<img width="1251" alt="image" src="https://user-images.githubusercontent.com/22118549/173860664-5c06b45b-dadf-424e-bc31-f81e1fa8349e.png">

<img width="1252" alt="image" src="https://user-images.githubusercontent.com/22118549/173861159-e5febf5c-80fc-47b9-bba6-0787baf7c27b.png">

### Steps to Reproduce
- Create a workload 
```sh
tanzu apps workload create pet-clinic --git-repo https://github.com/sample-accelerators/spring-petclinic --type web --app spring-petclinic --git-commit 123 --git-branch main
```
- Update the workload 
```sh
tanzu apps workload update pet-clinic  --git-tag tap-1.2
```
- Delete the workload
```sh
tanzu apps workload delete pet-clinic -y
```
- Create the workload without `--git-tag`, `--git-commit` and `--git-branch`
See the error
```sh
Error: [--git-branch, --git-tag]: Required value: expected exactly one, got neither
Error: exit status 1
```

### Version (Apps plugin version, Version of K8s running on cluster)
Put the output of the following commad
```sh
tanzu version && tanzu apps version

version: v0.11.1
buildDate: 2022-02-14
sha: 4d578570
v0.0.0-dev
```

**Comment by heyjcollins** [comment]
> when updating commit field, tag field is deleted. Same if updating tag, then commit would be deleted
In practice, isn't providing `commit` AND `tag` redundant?
Should they be exclusive?
If both commit and tag are allowed, it's possible to pass a commit value that doesn't align with the tag.
And although it looks as if the build succeeds, it's unclear which code iteration was compiled.

**Comment by warango4** [comment]
@heyjcollins so we should not allow to specify a tag alongside a commit?

**Comment by heyjcollins** [comment]
**always required:**
- `--git-repo`

**supported (allowed) combination:**
- `--git-commit` and `--git-branch`

**unsupported (disallowed) combinations:**
- `--git-branch` and `--git-tag` and `--git-commit`
- `--git-tag` and `--git-commit`
- `--git-branch` and `--git-tag`

**unsupported error messages:**
- `[--git-branch, --git-tag, --git-commit]: Required value: expected exactly --git-branch,  --git-branch AND --git-commit,  --git-tag, got unsupported combination (pass --git-branch "" or --git-tag ""  or --git-commit "" to unset)`
