### ISSUE TITLE
workload list --namespace bogus-namespace returns "no workloads found"

### ISSUE THREAD

**Issue by heyjcollins** [vmware-tanzu/apps-cli-plugin#18]
### Please fill out the issue checklist below and provide ALL the requested information.

- [X] I reviewed open and closed Github issues that may be related to my problem.
- [X] I am reporting a bug that others will be able to reproduce.

### Describe the bug
When user attempts to run workload list against a namespace that doesn't exist, the plugin returns: "No workloads found" and exits 0.

While it's true that no workloads would be found in a non-existent namespace, it hides the fact that the namespace name provided either doesn't exist (or the user doesn't have permissions to see the contents of the namespace provided).
If the user misspelled the namespace, the current response doesn't make that obvious.

When the namespace doesn't exist, the command should exit 1 with a helpful error message.
If there's a permissions issue for the namespace, that's distinguishable from the namespace not existing, the command should exit 1 with a different helpful error message.

If the plugin is unable to distinguish between the two, the command should exit 1 with a helpful error message that combines the possible issues using "or".

#### Current:
```
tanzu apps workload list --namespace foo
No workloads found.
```

#### Proposed (@danfein please refine as you see fit):
```
tanzu apps workload list --namespace foo

Error: namespace "foo" not found
Error: exit status 1

✖  exit status 1
```

#### Proposed - user doesn't have permissions to inspect namespace contents:
```
tanzu apps workload list --namespace foo

Error: user "user-name" has insufficient permissions to view namespace "foo"
Error: exit status 1

✖  exit status 1
```

#### Proposed - if doesn't exist and insufficient permissions are indistinguishable:
```
tanzu apps workload list --namespace foo

Error: either namespace "foo" not found or user "user-name" has insufficient permissions to view namespace "foo"
Error: exit status 1

✖  exit status 1
```

### Steps to Reproduce
tanzu apps workload list --namespace bogus-namespace

### Version (Apps plugin version, Version of K8s running on cluster)
all versions

**Comment by danfein** [comment]
Talked with Shash, It sounds like it is not possible to differentiate between `doesn't exist` and `no permissions`

Picking up from Josh's proposed combo text, I would propose a slightly shorter form: 

```
Error: namespace "foo" not found, it may not exist or user does not have permissions to read it.
```

**Comment by heyjcollins** [comment]
## Acceptance
correct exit code and message for list command targeting namespace that doesn't exist is confirmed:
```
ta list -n bogus-namespace
Error: namespace "bogus-namespace" not found, it may not exist or user does not have permissions to read it.
Error: exit status 1

✖  exit status 1
```

confirmed list command against namespace which does contain workloads works as expected (no regression).

confirmed list command against namespace which contains no workloads exits 0 with `No workloads found.` message
