### ISSUE TITLE
apply command is recommended in output from `workload create`

### ISSUE THREAD

**Issue by heyjcollins** [vmware-tanzu/apps-cli-plugin#181]
### Description of problem

With the deprecation of `workload update`, we need to increase discoverability of `workload apply` as the vehicle for making subsequent updates to the workload

### Proposed solution

```gherkin
Given I'm an app dev with access to a TAP-enabled cluster
When I run "tanzu apps workload create my-app"
Then I see an info message recommending the use of the "apply" command for updating the workload
```

### Example
```
%tanzu apps workload create my-app3 -f foo.yaml
Create workload:
      1 + |---
      2 + |apiVersion: carto.run/v1alpha1
      3 + |kind: Workload
      4 + |metadata:
      5 + |  labels:
      6 + |    apps.tanzu.vmware.com/workload-type: web
      7 + |  name: my-app3
      8 + |  namespace: ns1
      9 + |spec:
     10 + |  env:
     11 + |  - name: foo
     12 + |    value: bae
     13 + |  source:
     14 + |    image: gcr.io/pivotal-knative/jc-apps:latest@sha256:5ad9079b0f97a893e8feecd0adf683444cb5c29c8a32e427bef6a67fe019e487

? Do you want to create this workload? Yes
Created workload "my-app3"

To see logs:   "tanzu apps workload tail my-app3"
To get status: "tanzu apps workload get my-app3"
To make updates: "tanzu apps workload apply my-app3"
```
### Describe alternatives you've considered
providing the suggestion in the output from `tanzu apps workload get` - we may do this separately

### Additional context
cc @danfein

**Comment by danfein** [comment]
The original intent of the notifications pattern was to be a signpost pointing the way to the thing folks would most likely want to do next. 

I am less confident that the first thing someone would do after creating an app would be to update it. I could see putting the notification in the workload get output, to create a path that looks like 

`create an app > check on the app and notice something amiss > update the app`

With the current update command going away, the deprecation message should help folks who default to the old command. For folks who are looking for a command, the help text provides helpful information.

All of this to say, I am hesitant to add a persistent third line to the notification section, with the main concern being overloading the notifications.

**Comment by heyjcollins** [comment]
Closing this without implementing because we already recommend using`apply` in the deprecation message that's displayed when a user invokes `tanzu apps update`
