### ISSUE TITLE
workload list --output does not show all workloads in namespace

### ISSUE THREAD

**Issue by warango4** [vmware-tanzu/apps-cli-plugin#182]
### Please fill out the issue checklist below and provide ALL the requested information.

- [x] I reviewed open and closed Github issues that may be related to my problem.
- [x] I am reporting a bug that others will be able to reproduce.

### Describe the bug

When using workload list with --output flag, the list shows the same workload. In other words, the same workload is printed several times without showing info about any other workload.

### Expected behavior

this command should show all the workloads in the specified namespace or all namespaces, shouldn't print the same workload each time.

### Steps to Reproduce
- create various workloads (under default namespace or any other namespace of your preference)
- list the workloads, verify there is more than one. 
- list workloads with output and save the output in a file for better visualization
  - `tanzu apps workload list -o json > output.txt`
- check in the file, the last workload that was listed in the second step is the only one that's going to appear, as many times as workloads you have in your namespace. 

### Screenshots
![image](https://user-images.githubusercontent.com/22118549/173982192-a4e36f33-bc4f-4a65-942b-43a436892595.png)

<img width="748" alt="image" src="https://user-images.githubusercontent.com/22118549/173982249-677bfe98-9550-463e-b113-284c7f55eaea.png">

### Version (Apps plugin version, Version of K8s running on cluster)
Put the output of the following commad
```sh
tanzu version && tanzu apps version

version: v0.11.1
buildDate: 2022-02-14
sha: 4d578570
v0.0.0-dev
```

**Comment by heyjcollins** [comment]
This issue can be reproduced in v0.6.0.
The `--output` flag for this command didn't exist in `v0.5.1`.
