### ISSUE TITLE
workload get is recommended twice in create/update/apply if workload fails to become ready under wait flag

### ISSUE THREAD

**Issue by warango4** [vmware-tanzu/apps-cli-plugin#183]
### Please fill out the issue checklist below and provide ALL the requested information.

- [x] I reviewed open and closed Github issues that may be related to my problem.
- [x] I am reporting a bug that others will be able to reproduce.

### Describe the bug
When creating/updating/applying with `--wait` flag, if workload fails to become ready, the usage of workload get is printed twice.
Once in the hint to follow up commands, and one after the error appears. 

### Expected behavior

Now that a hint is shown once the command is sent, there is no need to show a second message indicating the usage of workload get in the error. This may seem redundant. 

### Steps to Reproduce
- create/update/apply a workload and use wait flag
  - `taw update spring-pet-clinic --git-tag not-real-tag-2 --wait --wait-timeout 1m`
- check there are two info messages pointing to use workload get

### Screenshots
![image](https://user-images.githubusercontent.com/22118549/173983513-88037837-94ed-4f4a-b8b8-2960a0b99e82.png)

### Version (Apps plugin version, Version of K8s running on cluster)
Put the output of the following commad
```sh
tanzu version && tanzu apps version

version: v0.11.1
buildDate: 2022-02-14
sha: 4d578570
v0.0.0-dev
```

**Comment by heyjcollins** [comment]
Cannot repro in previous release `v0.6.1`. 

This bug only occurs if/when the --wait-timeout period is exceeded

**Comment by heyjcollins** [comment]
Because we now display:
```
To see logs:   "tanzu apps workload tail aaa34"
To get status: "tanzu apps workload get aaa34"
```
unconditionally in the output from workload create/update/apply...

Let's remove the code which controls the display of `To view status run: tanzu apps workload get aaa34 --namespace ns1` completely.
