### ISSUE TITLE
tanzu apps workload create cannot use '--local-path' with private registry

### ISSUE THREAD

**Issue by heyjcollins** [vmware-tanzu/apps-cli-plugin#19]
### Description of problem
Many enterprises leverage a private intermediate signing authority to issue/manage their certificates. This intermediate CA cert must be distributed to all systems participating in the PKI. 

When they deploy a private image registry such as harbor, all k8s clusters and clients interacting directly with the registry require this intermediate CA. 

There's work underway to add support for private CA's to the various components of TAP on the server side, but when using the `tanzu apps workload create xxx --local-path . ` command to create a workload from sources on developer workstation, it surfaces an issue in that there's no way to configure the tanzu CLI to pick up local CA certificates.

The most expeditious flow for demonstration of TAP accelerators is to create a workload directly off the downloaded accelerator assets. This surfaces the issue in that a developer cannot do this with TAP today if they are using private enterprise certificates to protect their registry.

Our only option now is to apply a series of TAP server-side workarounds to deploy enterprise CAs server-side, create a git-repo push sources to this location and finally use the `--git-repo` option to get workloads to create in TAP today when deployed against a private / enterprise registry.

### Proposed solution

Provide tanzu cli with an "--insecure-skip-tls-verify" option -- not aligned with our "secure always" narrative
Provide tanzu cli with a "--ca-certs" option

### Additional context
Originally submitted by @tfynes-pivotal

**Comment by heyjcollins** [comment]
Original comment from @scothis:

> there's no way to configure the tanzu CLI to pick up local CA certificates

While I agree that it should be easier to specify additional CA certs for the cli, I disagree with the above assertion. If a CA is trusted by the OS, it will also be trusted by our cli. While an OS specific operation requiring root/admin privileges, adding an enterprise CA to the system trust store will provide a better overall UX for these users than needing to specify the same flag for every invocation.

**Comment by atmandhol** [comment]
This will be implemented by https://github.com/vmware-tanzu/apps-cli-plugin/issues/116

**Comment by atmandhol** [comment]
Closing this issue as support for providing CA cert path was added by https://github.com/vmware-tanzu/apps-cli-plugin/pull/220 and will be available in version 0.8.0.
