### ISSUE TITLE
Add source information to workload get output

### ISSUE THREAD

**Issue by heyjcollins** [vmware-tanzu/apps-cli-plugin#21]
### Description of problem

There have been cases in tap-assist where folks lose track of which workload is from which source, or where they use the wrong repo/branch and have a hard time troubleshooting the resulting unexpected behavior.

### Proposed solution

As an application developer, when I inspect a workload via workload get I would like to know what source code / image is currently used by the workload so that I can verify that the latest version has been picked up

As an application operator, when I inspect a workload via workload get I would like to know what source code / image is currently used by the workload so that I can trace back a given workload when troubleshooting or auditing

```gherkin
Given a workload has been deployed to my target cluster
When I inspect the workload via workload get
Then I can see what source code / image is currently used by the workload so that I can trace back a given workload when troubleshooting or auditing
```

### Describe alternatives you've considered
`tanzu apps workload get NAME --export` will return that that information, but as yaml or json - but those formats are less human friendly than providing name/value pairings.

### UX
If code is sourced from a git repo
```
$tanzu apps workload get tanzu-java-web-app -n tap-install
Name:   tanzu-java-web-app: Ready
---
lastTransitionTime:  "2022-01-05T06:57:18Z"
message:             ""
reason:              Ready [waiting for value at path]
status:              "True"
type:                Ready

Source:   https://github.com/spring-projects/spring-petclinic
Branch:   main
Tag   :   v1.1.0
Commit:   g5na5c
```

If code is sourced from local code
```
Source:        Local source code
Source-image:  Source:gcr.io/pivotal-knative/jc-apps:latest@sha256:3ba565457e5b5c64f5956bcb7ef9080fb3d4083f0a7c5826b48832507623c177
Updated:       23min 
```

If code is sourced from a prebuild image
```
Source:    Image
Image:     gcr.io/pivotal-knative/jc-apps:latest@sha256:3ba565457e5b5c64f5956bcb7ef9080fb3d4083f0a7c5826b48832507623c177 
Updated:   23min 
```

`Updated` — If possible to know, how long has it been since the last update from the source. The intent is to help folks know if their latest changes have been picked up. Talking to Wendy it sounds like this may not be easily knowable. 

### Additional context
Issue originally reported by @danfein

**Comment by heyjcollins** [comment]
comment originally submitted by @scothis:

@danfein please close this issue if the support as implement is sufficient for your ask.

**Comment by heyjcollins** [comment]
comment originally submitted by @danfein:

Chatted with @scothis and the team, decided to hold back on this until additional information on what is in-use is available from cartographer. Showing what is specified only risks misrepresenting the state of things to users.

**Comment by heyjcollins** [comment]
@danfein or @scothis - Can you provide an example of how the current proposal could misrepresent what is "in-use" and what could cause this discrepancy?

**Comment by danfein** [comment]
Updated based on using the cartographer provided information rather than the workload.yml

## Git source

```
source:     git
url:        https://github.com/spring-projects/spring-petclinic
sub-path:   project1
branch:     main
tag:        v1.1.0
commit:     g5na5s
```

## Local source

```
source:   local
image:    gcr.io/pivotal-knative/jc-apps:latest@sha256: 3ba565457e5b5c64f5956bcb7ef9080fb3d4083f0a7c5826b48832507623c17

```

## Image source

```
source:   image
image:    gcr.io/pivotal-knative/jc-apps:latest@sha256: 3ba565457e5b5c64f5956bcb7ef9080fb3d4083f0a7c5826b48832507623c177

```

**Comment by danfein** [comment]
@heyjcollins The original issue used the workload yaml as the source of truth, and would tell you what the last thing you requested the workload use was. 

If you were to update the workload, but the changes didn't go thru, the previous source would still be in use and we would report the newest requested source, which would be incorrect. 

By using cartographer as the source of truth we should be able to know what is in use.

**Comment by scothis** [comment]
> ```
> source:   local
> ```

This is a concept that exists within the CLI when creating a source image. Once that local source code is published to an image, it's a source image. Cartographer has no notion of "local" source.

> ```
> source:   image
> ```

Based on the other context, this isn't a source image (`.spec.source.image` but an image image (`.spec.image`). Labeling it as source is misleading as there is nothing to build, this image is pre-built.
