### ISSUE TITLE
Show workload type in workload list and get output

### ISSUE THREAD

**Issue by atmandhol** [vmware-tanzu/apps-cli-plugin#223]
### Description of problem

Output of the `apps workload list` and `apps workload get` commands are missing the workload type information.
 
![Screen Shot 2022-07-17 at 10 52 38 PM](https://user-images.githubusercontent.com/7171846/179438708-fa9c4dd9-8ae4-49b7-a636-20a885984e67.png)

![Screen Shot 2022-07-17 at 10 54 47 PM](https://user-images.githubusercontent.com/7171846/179438852-4d3e8fd6-f85a-4348-a3a1-6846491ef5d8.png)

### Proposed solution

Add the workload `type` information in workload list and get output

**Comment by danfein** [comment]
Talked with @shaheerkootteeri - Proposed column order for list

`NAME   TYPE   APP   STATUS   AGE`

When there is no value for type we will display `<empty>`

**Comment by danfein** [comment]
Proposed `workload get` 

```
$tanzu apps workload get tanzu-java-web-app
---
Name: tanzu-java-web-app: Ready
---
Workload
type:   web

Source
...
```

The workload section could also be used to house other information such as
* type
* namespace
* cluster
* age
* URL
* update strategy
* schedule (for cronjob workloads)
* live view on/off
* debug on/off
* resource usage

**Comment by danfein** [comment]
After talking with @heyjcollins - we decided to use `overview` rather than `workload` as the title for the new section.
