### ISSUE TITLE
Workload get output pod status should mimic kubectl output

### ISSUE THREAD

**Issue by atmandhol** [vmware-tanzu/apps-cli-plugin#224]
### Description of problem

`tanzu apps workload get` shows the status of `Pending` when a build is running. The status `Pending` while accurate, is not very helpful. 

![Screen Shot 2022-07-17 at 11 02 38 PM](https://user-images.githubusercontent.com/7171846/179439380-a757461e-617d-4227-8146-fbca1555f4e4.png)

### Proposed solution
`apps` plugin should mimic the output of `kubectl` as shown in the screenshot below. It should show `init` container information when the pods are not in a `completed` or `succeeded` status.

![Screen Shot 2022-07-17 at 11 04 55 PM](https://user-images.githubusercontent.com/7171846/179439519-9963c915-be30-4e5f-9d60-15b33984ccfe.png)

cc @danfein for design recommendations.

**Comment by danfein** [comment]
Holding - pending outcome of tech investigation into feasibility of integrating kubectl library to enable reading the required information

**Comment by heyjcollins** [comment]
### AC
created a new namepsace to assure all pods are associated with a new app to be deployed to that namespace using `tanzu apps workload apply....`
Then compared output of `watch kubectl get pods` with `watch tanzu apps workload get app-name`

The table values in the output from kubectl were found to be consistent with those displayed in the "Pods" section of workload get output.

for example:
```
🛶 Pods
   NAME                        READY   STATUS     RESTARTS   AGE
   ns3-app-build-1-build-pod   0/1     Init:4/6   0          30s
```

```
Every 2.0s: kubectl get pods              collinsjo-a02.vmware.com: Thu Sep  1 14:49:52 2022

NAME                        READY   STATUS     RESTARTS   AGE
ns3-app-build-1-build-pod   0/1     Init:4/6   0          30s
```
