### ISSUE TITLE
Improve feedback in `--local-path` workflow by showing the size of the local source being uploaded

### ISSUE THREAD

**Issue by atmandhol** [vmware-tanzu/apps-cli-plugin#225]
### Description of problem

In the `--local-path` workflow, there is no way to know what is the size of the local source bundle that is being uploaded.

![Screen Shot 2022-07-17 at 11 08 52 PM](https://user-images.githubusercontent.com/7171846/179439816-085131c4-8f74-4d9e-871c-5c35dd72cb90.png)

### Proposed solution

```gherkin
Given the developer is using the --local-path workflow to create workloads
When they run tanzu apps workload apply/create with --local-path and upload their local source to a registry
Then the size of the local source bundle that is being uploaded, and its progress is shown in the output
```

#### Bonus
- Add a progress bar to show the progress of the upload.

### Additional context
You can use the following imgpkg feature to get size uploaded information.
https://github.com/vmware-tanzu/carvel-imgpkg/blob/develop/pkg/imgpkg/registry/with_progress.go

cc @danfein for the design recommendation on how to display that information.

**Comment by danfein** [comment]
Recommendation

```
Image size: 12Mb
```

**Comment by atmandhol** [comment]
Apps plugin uses `imgpkg` as library internally. This issue is blocked till the issue https://github.com/vmware-tanzu/carvel-imgpkg/issues/420 is addressed on `imgpkg`.
