### ISSUE TITLE
Indent content below each section heading in workload get output to improve readability (possibly also `clustersupplychain get`)

### ISSUE THREAD

**Issue by heyjcollins** [vmware-tanzu/apps-cli-plugin#228]
### Description of problem

The volume of content included in the output from `workload get` has increased significantly with several sections and will likely increase further over time.

The section headings aren't currently standing out as headings and parsing the output requires effort.

### Proposed solution

Indent the content below each section heading to make the parent/child relationship visually obvious, enabling viewers to more easily scan the content and focus on the section relevant to their current need.

### Example
**Current output:**
```
tanzu apps workload get app1
---
# app1: Ready
---
Source
type:    source image
image:   gcr.io/pivotal-knative/jc-apps:latest@sha256:5ad9079b0f97a893e8feecd0adf683444cb5c29c8a32e427bef6a67fe019e487

Supply Chain
name:          source-to-url
last update:   19h
ready:         True

RESOURCE          READY   TIME
source-provider   True    19h
deliverable       True    19h
image-builder     True    19h
config-provider   True    19h
app-config        True    19h
config-writer     True    19h

Issues
No issues reported.

Pods
NAME                                     STATUS      RESTARTS   AGE
app1-00001-deployment-58d84d7d5d-2trnp   Running     0          19h
app1-build-1-build-pod                   Succeeded   0          19h
app1-config-writer-5p5df-pod             Succeeded   0          19h

Knative Services
NAME   READY   URL
app1   Ready   http://app1.ns1.127.0.0.1.nip.io

To see logs: "tanzu apps workload tail app1"
```

**Proposed output (3 space indent)**

```
tanzu apps workload get app1
---
# app1: Ready
---
Source
   type:    source image
   image:   gcr.io/pivotal-knative/jc- 
   apps:latest@sha256:5ad9079b0f97a893e8feecd0adf683444cb5c29c8a32e427bef6a67fe019e487

Supply Chain
   name:          source-to-url
   last update:   19h
   ready:         True

   RESOURCE          READY   TIME
   source-provider   True    19h
   deliverable       True    19h
   image-builder     True    19h
   config-provider   True    19h
   app-config        True    19h
   config-writer     True    19h

   Issues
   No issues reported.

Pods
   NAME                                     STATUS      RESTARTS   AGE
   app1-00001-deployment-58d84d7d5d-2trnp   Running     0          19h
   app1-build-1-build-pod                   Succeeded   0          19h
   app1-config-writer-5p5df-pod             Succeeded   0          19h

Knative Services
   NAME   READY   URL
   app1   Ready   http://app1.ns1.127.0.0.1.nip.io

To see logs: "tanzu apps workload tail app1"
```

### Describe alternatives you've considered
Bold / Colorize headings -- I see indenting as a stronger indicator of visual hierarchy. Additionally, we can reserve bold/color to draw attention to important information within the sections (e.g. error status). One negative of the indenting however, is that it increases the character count for each line and increases opportunities for text wrapping.

I'd be interested in other opinions and suggestions.

**Comment by danfein** [comment]
Great idea, should help with clarifying the grouping in places like supply chain / issues, where there are multiple sections under a shared header. 

@atmandhol and I had also talked about a related idea around using more color to call attention to important bits of information such as health / status within the supply chain or resource tables.

**Comment by heyjcollins** [comment]
@danfein - 
> I would be inclined to use three spaces rather than four, just because it is the amount we use to separate elements in tables and key:value pairs

I originally used 3 spaces and found the indenting to be less effective, then bumped to 4 spaces.
Here's both (at the end of this comment) so you can compare. Please feel free to make the final call and I'll adjust the original issue description accordingly.

>  had also talked about a related idea around using more color to call attention to important bits of information such as health / status within the supply chain or resource tables.

Please describe any section(s)/conditions which should be colorized and/or bolded (that's not already been taken care of via other issue(s), and we can wrap those changes in while implementing the indentation.

**3 space indentation**
```
tanzu apps workload get app1
---
# app1: Ready
---
Source
   type:    source image
   image:   gcr.io/pivotal-knative/jc- 
   apps:latest@sha256:5ad9079b0f97a893e8feecd0adf683444cb5c29c8a32e427bef6a67fe019e487

Supply Chain
   name:          source-to-url
   last update:   19h
   ready:         True

   RESOURCE          READY   TIME
   source-provider   True    19h
   deliverable       True    19h
   image-builder     True    19h
   config-provider   True    19h
   app-config        True    19h
   config-writer     True    19h

   Issues
   No issues reported.

Pods
   NAME                                     STATUS      RESTARTS   AGE
   app1-00001-deployment-58d84d7d5d-2trnp   Running     0          19h
   app1-build-1-build-pod                   Succeeded   0          19h
   app1-config-writer-5p5df-pod             Succeeded   0          19h

Knative Services
   NAME   READY   URL
   app1   Ready   http://app1.ns1.127.0.0.1.nip.io

To see logs: "tanzu apps workload tail app1"
```

**4 space indentation***
```
tanzu apps workload get app1
---
# app1: Ready
---
Source
    type:    source image
    image:   gcr.io/pivotal-knative/jc- 
    apps:latest@sha256:5ad9079b0f97a893e8feecd0adf683444cb5c29c8a32e427bef6a67fe019e487

Supply Chain
    name:          source-to-url
    last update:   19h
    ready:         True

    RESOURCE          READY   TIME
    source-provider   True    19h
    deliverable       True    19h
    image-builder     True    19h
    config-provider   True    19h
    app-config        True    19h
    config-writer     True    19h

    Issues
    No issues reported.

Pods
    NAME                                     STATUS      RESTARTS   AGE
    app1-00001-deployment-58d84d7d5d-2trnp   Running     0          19h
    app1-build-1-build-pod                   Succeeded   0          19h
    app1-config-writer-5p5df-pod             Succeeded   0          19h

Knative Services
    NAME   READY   URL
    app1   Ready   http://app1.ns1.127.0.0.1.nip.io

To see logs: "tanzu apps workload tail app1"
```

**Comment by evankanderson** [comment]
One extra consideration here is whether adding whitespace at the beginning of lines might break anyone who’s using text-processing tools on the output.

It looks like the current `workload get` output mixes different content types so that’s probably less of an issue with other tools like `kubectl`, so I’m not too worried about it in this case, but it's worth thinking about whether there's any sort of output contracts when changing CLI output.
