### ISSUE TITLE
`tanzu apps deliverable get` returns deliverable details

### ISSUE THREAD

**Issue by heyjcollins** [vmware-tanzu/apps-cli-plugin#240]
### Description of problem

**PLACEHOLDER** -- details pending...

<Please describe the problem your feature request is trying to solve>

### Proposed solution

<Please describe your proposed solution, preferably in the following style:>

```gherkin
Given <Some Condition>
When <Something Happens>
Then <This other thing should happen?>
```

### Example

<Code snippets that illustrate the when/then blocks>

**Comment by atmandhol** [comment]
Deliverable info is now included in workload get so we decided to not implement a separate sub-command for this for now.
