### ISSUE TITLE
Add StampedRef Resource Kind and Name in workload get output

### ISSUE THREAD

**Issue by atmandhol** [vmware-tanzu/apps-cli-plugin#248]
### Description of problem

Currently, we show Supply chain Resources, Ready, Healthy and Time columns in workload get output. It would be great to see an additional column that shows which resource was stamped out by the supply chain.

![Screen Shot 2022-08-02 at 5 48 58 PM](https://user-images.githubusercontent.com/7171846/182479435-933480fc-0f1f-4cd0-8517-2b297e53896d.png)

### Proposed solution

Add a column before Ready column that shows the Kind and Name of the resource stamped out by the supply chain.

### Example

```
   RESOURCE          OUTPUT                              READY   HEALTHY   TIME
   source-provider   ImageRepository/reg-test5           True    True      4d
   deliverable       Deliverable/reg-test5               True    True      4d
   image-builder     Image/reg-test5                     True    True      4d
   config-provider   PodIntent/reg-test5                 True    True      4d
   app-config        ConfigMap/reg-test5                 True    True      4d
   config-writer     Runnable/reg-test5-config-writer    True    True      4d
```

cc @danfein for design input related to column name

**Comment by danfein** [comment]
Proposed change: run the output column last

Output values are a little longer running, and may be variable width, running it last will keep ready / health / time aligned between the supply and delivery tables. 

Also if someone is `watch`ing the workload get the fields can populate over time without shifting the table columns around.

Output is also a summary / last thing that happens for a given resource, which feels like a natural last-column item. 

```
   RESOURCE          READY   HEALTHY   TIME   OUTPUT
   source-provider   True    True      4d     ImageRepository/reg-test5
   deliverable       True    True      4d     Deliverable/reg-test5
   image-builder     True    True      4d     Image/reg-test5
   config-provider   True    True      4d     PodIntent/reg-test5
   app-config        True    True      4d     ConfigMap/reg-test5
   config-writer     True    True      4d     Runnable/reg-test5-config-writer
```

**Comment by heyjcollins** [comment]
### AC
**LGTM**

* Stamped out resources column (OUTPUT) confirmed in the output:
![Screen Shot 2022-08-08 at 5 45 53 PM](https://user-images.githubusercontent.com/37092016/183538849-d2730dd2-5e8a-43ad-b4c6-288fea648c28.png)
* no stamped out resource created for a given step displays `not found`: 
![Screen Shot 2022-08-08 at 5 48 58 PM](https://user-images.githubusercontent.com/37092016/183539058-a4d422fc-87b6-4878-981d-13c037db0f9a.png)
* confirmed copy/paste of `OUTPUT` column value into `kubectl describe...` returns without error:
![Screen Shot 2022-08-08 at 5 51 58 PM](https://user-images.githubusercontent.com/37092016/183539253-a63ff830-0721-4d0f-900c-5779c6bf7a90.png)
