### ISSUE TITLE
workload get includes deliverable information when available

### ISSUE THREAD

**Issue by danfein** [vmware-tanzu/apps-cli-plugin#251]
### Description of problem

Workload get includes information about the supply chain process, but does not surface the delivery process information.

The supply chain information can help troubleshoot stuck deployments, and including the delivery information can be part of telling the user the story of the exiting journey thru the the machinery of TAP. 

### Proposed solution

```gherkin
Given I `get` a workload
When the information returns
Then I should see a table with the cluster delivery information
```

### Example

```
Supply chain  
   name:   source-to-url

   RESOURCE           READY   HEALTHY   TIME     OUTPUT  
   Source Provider    True    True      9m ago   ImageRepository/web3
   Image Builder      True    True      8m ago   Deliverable/web3
   Config Provider    True    True      7m ago   Image/web3
   App Config         True    True      6m ago   not found
   Config Writer      True    True      6m ago   not found
 
Delivery 
   name:   delivery-basic

   RESOURCE           READY   HEALTHY   TIME     OUTPUT
   delivery-source    True    True      9m ago   not found
   source-scanner     True    True      8m ago   not found
   source             True    True      7m ago   not found
   testing-pipeline   True    True      6m ago   not found

Messages
   No Messages Found

```

On an **iterate** cluster, the supply chain and delivery information should be available, and both tables can be shown.
On a **build** cluster, the supply chain info would be available, and the delivery table would be omitted
On a **run** cluster, the delivery information would be  available, and the supply table would be omitted

The **messages** section should have messages consolidated from both the workload and deliverable objects.

### Describe alternatives you've considered
Combining supply and delivery steps in a single table. 
* saves a few lines in the workload-get output
* talking to @atmandhol it sounds like it would add complexity to the situations where you would only be able to see either supply or delivery stages, and when outputting yaml.

```
Deployment  
   Supply chain:   source-to-url
   Delivery chain: delivery-basic

   RESOURCE           READY   HEALTH   TIME      OUTPUT
   Source Provider    True    True     9m ago    <value>
   Image Builder      True    True     8m ago    <value>
   Config Provider    True    True     7m ago    <value>
   App Config         True    True     6m ago    <value>
   Config Writer      True    True     6m ago    <value>
   Delivery Source    True    True     6m ago    <value>
   Source Scanner     True    True     6m ago    <value>
   Source             True    True     6m ago    <value>
   Testing Pipeline   True    True     6m ago    <value>

Messages
   No Messages Found


```

**Comment by danfein** [comment]
## Additional Cases

### Build cluster context
Assumption: that the delivery name and resources would not be visible from the build cluster. 
```
Supply chain  
   name:   source-to-url

   RESOURCE           READY   HEALTHY   TIME     OUTPUT  
   Source Provider    True    True      9m ago   ImageRepository/web3
   Image Builder      True    True      8m ago   Deliverable/web3
   Config Provider    True    True      7m ago   Image/web3
   App Config         True    True      6m ago   not found
   Config Writer      True    True      6m ago   not found
 
Delivery 
   name:   not found

   Delivery resources not found
```


### Run cluster context
Assumption: the supply chain could be determined from the workload.yaml, but the state of the resources would not be visible from the run cluster. 

```
Supply chain  
   name:   source-to-url

   Supply chain resources not found 
 
Delivery 
   name:   delivery-basic

   RESOURCE           READY   HEALTHY   TIME     OUTPUT
   delivery-source    True    True      9m ago   not found
   source-scanner     True    True      8m ago   not found
   source             True    True      7m ago   not found
   testing-pipeline   True    True      6m ago   not found
```

### Also considered

```
   Supply chain resources not found on this cluster
```
- left the cluster out, not sure if there are cases where namespaces might divide run/build, or other reasons why "on this cluster" might be misleading.

**Comment by heyjcollins** [comment]
##AC
Failed because message prefix is being displayed even when there's no message to display (it should be hidden).

### Showing/Hiding content in the "Messages" section
If there is no `HealthyCondition` or `Ready` message associated with the Workload and/or Deliverable, the "Workload" and/or "Deliverable" message line should not be included in the output.

* no `HealthyCondition` or `Ready` message associated with either:
   ```
   Messages
      No Messages Found 
   ```
* a `HealthyCondition` or `Ready` message associated with only Workload
   ```
   Messages
      Workload [HealthyConditionRule]:   message content here....
   ```
* a `HealthyCondition` or `Ready` message associated with only Deliverable
   ```
   Messages
      Deliverable [HealthyConditionRule]:   message content here....
   ```
* a `HealthyCondition` or `Ready` message associated with both Workload AND Deliverable
   ```
   Messages
      Workload [HealthyConditionRule]:   message content here....  
      Deliverable [HealthyConditionRule]:   message content here....
   ```
