### ISSUE TITLE
Issues section is showing HealthyConditionRule with empty message

### ISSUE THREAD

**Issue by warango4** [vmware-tanzu/apps-cli-plugin#253]
### Please fill out the issue checklist below and provide ALL the requested information.

- [x] I reviewed open and closed Github issues that may be related to my problem.
- [x] I am reporting a bug that others will be able to reproduce.

### Describe the bug
`HealthyConditionRule` is being shown in `Issues` section for `workload get` ouput when it's empty

### Expected behavior
It shouldn't be shown if there is no info to show

### Steps to Reproduce
- Create a workload that will fail, like the example below
  - `$ tanzu apps wld apply java-web-app-mvn --param-yaml maven='{"artifactId": "demo", "version": "0.0.1-SNAPSHOT", "groupId": "com.example"}' --type web --app java-web-app -y`
- Retrieve workload info
  - `$ tanzu apps workload get java-web-app-mvn`
- Check the issues section, it will show a `TemplateRejectedByAPIServer` issue and also a `HealthyConditionRule` that's empty

### Screenshots
![image](https://user-images.githubusercontent.com/22118549/182895618-38f71c34-537b-41e4-bd5b-f12962bbe1e5.png)

### Version (Apps plugin version, Version of K8s running on cluster)
Put the output of the following commad
```sh
tanzu version && tanzu apps version

version: v0.11.6
buildDate: 2022-05-20
sha: 90440e2b
v0.0.0-dev
```

**Comment by heyjcollins** [comment]
### AC
When there's no `HealthyConditionRule` to display for a workload, that row is no longer displayed in the output:
![Screen Shot 2022-08-08 at 5 59 37 PM](https://user-images.githubusercontent.com/37092016/183540062-7ce30584-6fc4-4c91-82b7-3c5ede0470d5.png)
