### ISSUE TITLE
Remove "deliverable" resource from the supply chain table displayed in `workload get` output

### ISSUE THREAD

**Issue by heyjcollins** [vmware-tanzu/apps-cli-plugin#257]
### Description of problem

The deliverable resource that's included in the "Supply Chain" resource table displayed in the output from `workload get` doesn't provide much value to users and should be removed.

1. the HealthRule for the deliverable is _always_ True (won't show False even if it's failed) - so not much actionable value can be had from it's inclusion as-is
   - in addition, the meaning/purpose of the deliverable step is not intuitively obvious to users and can cause confusion
1. as part of (#251), we will be adding the deliverable info in workload get as part of the (new/pending) `clusterDelivery` section, and messages from the deliverable will be displayed in the  `Messages` section and this additional content should account from the removal of deliverable from the supply chain table.
1.   The deliverable resource that's displayued in the "Supply Chain" section of `workload get` for a workload which was selected by part of the OOTB `source-to-url` supply chain 

### Proposed solution

remove the deliverable row from the supply chain table

```gherkin
Given my workload X has been deployed successfully to my target cluster via the `source-to-url` supply chain
When I run "tanzu apps workload get X"
Then I DO NOT see a `deliverable` resource row displayed in the Supply Chain resources table in the command output
```

### Example

```
ta get X
---
# X: Ready
---
...

Supply Chain
   name:          source-to-url
   last update:   42h
   ready:         True

   RESOURCE          READY   HEALTHY   TIME   OUTPUT
   source-provider   True    True      42h    GitRepository/app4
   image-builder     True    True      42h    Image/app4
   config-provider   True    True      42h    PodIntent/app4
   app-config        True    True      42h    ConfigMap/app4
   config-writer     True    True      42h    Runnable/app4-config-writer

   Messages
   No messages found.

...

To see logs: "tanzu apps workload tail X"
```

### Describe alternatives you've considered
Leaving the deliverable row as-is

### Additional context
#251 should be implemented prior to this issue.

**Comment by atmandhol** [comment]
We should remove all rows where the output.kind == "Deliverable".
Matching done on the Kind will be more accurate and less error prone than on the step name which can be anything the supply chain author wants.
