### ISSUE TITLE
Source image is uploaded when namespace is invalid for workload creation/apply 

### ISSUE THREAD

**Issue by shashwathi** [vmware-tanzu/apps-cli-plugin#271]
### Please fill out the issue checklist below and provide ALL the requested information.

- [x] I reviewed open and closed Github issues that may be related to my problem.
- [x] I am reporting a bug that others will be able to reproduce.

### Describe the bug
When user creates/applies workload from local-path and source-image flag in some non existent namesspace, source code/jar is uploaded to registry and then workload creation fails because namespace does not exist.

User has to setup namespace and then re-run the command but source image upload has already been done in the previous step.

### Expected behavior
Fail before source image upload because namespace does not exist. Preliminary name and namespace check should be done before triggering source image upload.

### Steps to Reproduce

```
tanzu apps workload create pet-img-5 --source-image gcr.io/something/helloworldtestjar:source --local-path pkg/source/testdata/helloworld.jar -n notexist

? Publish source in "pkg/source/testdata/helloworld.jar" to "gcr.io/something/helloworldtestjar:source"? It may be visible to others who can pull images from that repository Yes
Publishing source in "pkg/source/testdata/helloworld.jar" to "gcr.io/something/helloworldtestjar:source"...
Published source
Create workload:
      1 + |---
      2 + |apiVersion: carto.run/v1alpha1
      3 + |kind: Workload
      4 + |metadata:
      5 + |  name: pet-img-5
      6 + |  namespace: notexist
      7 + |spec:
      8 + |  source:
      9 + |    image: gcr.io/something/helloworldtestjar:source@sha256:980ab26419c9139b973daf1f2adc1ebacf91fcfd416769d03dd09768c12a1f1b

? Do you want to create this workload? Yes
Error: namespaces "notexist" not found
Error: exit status 1

✖  exit status 1 
```

### Version (Apps plugin version, Version of K8s running on cluster)
Put the output of the following commad
```sh
tanzu version && tanzu apps version
v0.8.0
```

**Comment by heyjcollins** [comment]
### AC:
```
ta apply ns3-app --local-path /Users/collinsjo/workspace/tanzu-java-web-app --source-image gcr.io/pivota
l-knative/jc-apps -n ns3 --type web -y
Error: namespace "ns3" not found, it may not exist or user does not have permissions to read it.
Error: exit status 1

✖  exit status 1
```
