### ISSUE TITLE
--local-path supports jar/zip

### ISSUE THREAD

**Issue by heyjcollins** [vmware-tanzu/apps-cli-plugin#29]
### Description of problem

There are processes/pipelines being utilized today which generate a jar/zip file artifact.

These pipelines will often pull in additional assets which aren't included in the application code itself, but which are necessary for the application function.
A subsequent next step is for the jar/zip of the app to be pushed to and run on a target environment.
Popular platforms such as Cloud Foundry support this workflow today (via the cf CLI). 

The apps plugin for the Tanzu CLI _does not_ support creating/updating/applying a workload from a local jar or zip directly.
The file must be unzipped beforehand. 
Requiring the jar be unzipped is not an expected step, it creates toil without value, and decreases efficiency.

### Proposed solution

```gherkin
Given I've got a JAR (or zipped) file containing all assets required to create a workload and I'm targeting a TAP-enabled workload cluster
When I run `tanzu apps workload create myapp -f path/to/my/myapp.jar...`
Then my workload create command exits 0 and I can validate the workload has run through the supply chain by viewing the workload details via `tanzu apps workload get...`
```

@danfein to provide UX here

### Additional context
* cc: @matthewmcnew @jigsheth57 may have additional context/thoughts on this issue
* from @scothis: 
  * It's worth mirroring the behavior of pack. https://github.com/buildpacks/pack/blob/3fc8e2220b584da76cd0227bbc211aae787e0e57/pkg/client/build.go#L596-L605

**Comment by heyjcollins** [comment]
Is there value in supporting other compression formats such as TAR files?
@matthewmcnew @jigsheth57

**Comment by matthewmcnew** [comment]
At this time pack/kp only support the zip format. So, I don't believe it is necessary to support other components in the apps plugin.

**Comment by danfein** [comment]
Help text update proposed 

```
 --local-path path                path to a directory, .zip, or .jar file containing workload source code 
```

current help text

```
 --local-path path                path on the local file system to a directory of source code to build for the workload
```
