### ISSUE TITLE
resources displayed in OUTPUT column in workload get  `supply chain` and `delivery` sections need to be disambiguated

### ISSUE THREAD

**Issue by heyjcollins** [vmware-tanzu/apps-cli-plugin#322]
### Please fill out the issue checklist below and provide ALL the requested information.

- [X] I reviewed open and closed Github issues that may be related to my problem.
- [X] I am reporting a bug that others will be able to reproduce.

### Describe the bug
We provided a reference to the stamped out resource associated with a given stage of the supply chain or delivery steps for a workload.

The intention of this was to provide an easy copy/paste flow a use could execute when troubleshooting.
The current format is `kind/name`.
For example, if the build failed, they could copy/paste the stamped out resource from the supply-chain OUTPUT column and `kubectl describe` it.

There were some changes to underlying apis which broke the intended troubleshooting path.
We learned that the only way to definitively reference the stamped out resource is to provide the fully qualified resource name rather than `Kind`

### Expected behavior
For example, when I copy past the `PodIntent/spring-sensors-bogus-consumer-web` into `kubectl describe`, I expect the kubeAPI to return the full description of that resource.

what actually happens today is:
```
kubectl describe PodIntent/spring-sensors-bogus-consumer-web
Warning: conventions.apps.tanzu.vmware.com/v1alpha1 PodIntent is deprecated; use conventions.carto.run/v1alpha1 PodIntent instead
Error from server (NotFound): podintents.conventions.apps.tanzu.vmware.com "spring-sensors-bogus-consumer-web" not found
```
### Steps to Reproduce
1. create a workload 
2. once it's running, run `tanzu apps workload get APPNAME`
3. copy the name of the stamped our resource in the OUTPUT column for the `config-provider` row of the table
4. kubectl describe it (e.g. `kubectl describe PodIntent/spring-sensors-bogus-consumer-web`)
5. notice the 'warning' message and note there's no describe output returned. 

### Proposed Solution - applies to both `supply chain` and `delivery` sections:
1. [ ] Change column headings from `RESOURCE    READY   HEALTHY   TIME   OUTPUT` ==>  `NAME    READY   HEALTHY   UPDATED   RESOURCE`
2. [ ] update the `RESOURCE column value to display the fully qualified resource ref rather than the `kind`
3. [ ] update command reference docs if/where the old output is displayed (eg. if there is example output)
4. [ ] provide a release note

example:
```
...
NAME               READY   HEALTHY   UPDATED    RESOURCE
source-provider    True    True      5d18h      gitrepositories.source.toolkit.fluxcd.io/spring-sensors-bogus-consumer-web
image-provider     True    True      44h        images.kpack.io/spring-sensors-bogus-consumer-web
config-provider    True    True      6d23h      podintents.conventions.carto.run/spring-sensors-bogus-consumer-web
...
```

**Comment by atmandhol** [comment]
Fixed by the MR: https://github.com/vmware-tanzu/apps-cli-plugin/pull/396
