### ISSUE TITLE
As an app dev I can pass a flag/value on `workload apply` to overwrite existing workload configuration on the target cluster with my local workload.yaml configuration

### ISSUE THREAD

**Issue by heyjcollins** [vmware-tanzu/apps-cli-plugin#336]
### Description of problem

We've made it easy to add or update fields/properties in the workload.yaml via `tanzu apps workload apply -f workload.yaml` but it's impossible to delete existing fields/properties (when removed from workload.yaml) via the same command.
Field deletion is only supported via flags currently (e.g. user who needs to remove envvar `foo: bar` must invoke `tanzu apps workload apply MY-APP --env foo-` 

Having to delete workload fields via direct invocation of Tanzu CLI apps plugin isn't intuitive for someone living/breathing in the IDE where they're used to invoking updates directly through the IDE interface itself where the workload.yaml is readily available to edit.

Today the apps plugin mutates/merges the workload object on the cluster when a dev `tanzu apps workload apply`s the workload.yaml on their local filesystem via `--file workload.yaml`. 

Originally, this was taken because we didn't want to assume the person invoking the change knew they had included all the fields required.
This may be helpful at times, but there are use cases where it adds significant friction (e.g. when using the IDE, the user has to hop out of their regular IDE-based flow, and invoke the apps CLI command directly). 

We need a way for the user to assert their workload definition as definitive and completely replace the version on-cluster.

### Proposed solution
Changing the behavior of the command introduces a breaking change so we must introduce a backward/forward-compatible means to replace workload configuration.
Introducing a flag/value enables end users to triggers the desired behavior without disrupting existing scripts/user-flows.

@doddatpivotal  suggested using  a `--force` flag which, when included, would tell the apps plugin to completely overwrite the existing workload object on the cluster with the workload.yaml on the developer's local filesystem (`tanzu apps workload apply -f workload.yaml --force`) - thank you for the suggestion Dodd :) 

Let's go with the spirit of Dodd's suggestion while optimizing for the ultimate goal of making "replace" the default behavior in the future.

Some ideas:
* ~~`--force`~~ (bool)
* ~~`--replace`~~ (bool)
* ~~`--always-overwrite`~~ (bool)
* ~~`--overwrite`~~ (bool)
* ~~`--file-merge`~~ (bool)
* `--update-strategy` (merge/replace)

**`--update-strategy`** is flag we've decided to go with.

#### Requirements:
1. [x] New flag `--update-strategy` added for sub-command `apply` (values: `merge`(default)/`replace`)
1. [x] Autocompletion for `--update-strategy [TAB]` >> merge, replace
1. [x] Deprecation warning displayed in `apply` output when `--file ...` flag is included:
  * `❗ WARNING: Configuration file update strategy is changing. By default, provided configuration files will replace rather than merge existing configuration. The change will take place in the January 2024 TAP release (use "--update-strategy" to control strategy explicitly).` 
1. [x] must be inclusive of `--file workload.yaml` (should throw an error if `--file workload.yaml` isn't included)
1. [ ] **Docs** Release Note > Deprecation notice regarding default behavior change from `merge` to `replace` in January 2024 TAP release
1. [ ] **Docs update** apply command reference - include complete explanation of the new flag, include examples for `--update-strategy merge` and `--update-strategy replace` 
1. [x] help for `--update-strategy` included in `tanzu apps apply -h` output
  * `--update-strategy          specify configuration file update strategy (supported strategies: merge[default], replace )`
 1. [x] `--update-strategy` doesn't make sense for `tanzu apps workload create` so if it's possible to not include it in `create -h` that is strongly desired (although passing `--update-strategy` would be a no-op either way so if it's technically impossible or exceptionally difficult to exclude it from `workload create` it would be sub-optimal, but not a deal-breaker.
1. [x] TO CONSIDER - read value from ENVVAR, when exists (name of envvar: `TANZU_APPS_UPDATE_STRATEGY`)

### Acceptance Criteria
```gherkin
Given I've created a workload that includes an environment variable "foo=bar"
When I remove
"
env:
  -name: foo
   value: bar
" 
from the workload.yaml on my filesystem and invoke "tanzu apps workload apply -f workload.yaml --update-strategy replace"
Then the workload object on the cluster is updated so it matches my local workload.yaml exactly (envvar foo=bar has been removed)
```

And make sure there's no regression WRT uploading updated source code and also passing in the workload.yaml
```gherkin
Given I've created a workload from local source that includes an environment variable "foo=bar"
e.g. "tanzu apps workload apply my-app --local-path . --source-image gcr.io/pivotal-knative/jc-apps --type web --env foo=bar --yes"
When I run "tanzu apps workload get my-app --export > workload.yaml" to save the current yaml to my local filesystem,
AND edit the workload.yaml to remove
"
env:
  -name: foo
   value: bar
"
AND make and save a change to the source code for my-app on my local filesystem
AND invoke "tanzu apps workload apply -f workload.yaml --update-strategy replace"
Then I can see in the diff output that the apps plugin uploaded the new code and replaced the current "spec.source.image" value with the new digest for the uploaded code
AND that the "foo=bar" env var has also been removed 
```

And current merge behavior hasn't regressed
```gherkin
Given I've created a workload named "bar" from local source
When download the current workload definition from the cluster via "tanzu apps workload get bar --export > bar.yaml"
and I remove
"
  name: bar
  namespace: default
  ...
spec:
  source:
    image: gcr.io/pivotal-knative/jc-apps:latest@sha256:2b0bb7ae0d403a98fac94d58ecdebf3272c336c9b7ba02a2f9cbb84604f2b833
" 
and save that as my local workload.yaml on my filesystem and invoke 
"tanzu apps workload apply -f bar.yaml --update-strategy merge"
OR
"tanzu apps workload apply -f bar.yaml"
Then the apps plugin will not make an update because there are no changes detected 
```

And file validation hasn't regressed when `replace` strategy is invoked
```gherkin
Given I've created a workload "bar" from local source
When download the current workload definition from the cluster 
and I remove required "name" field 
"
  name: bar
  ...
from the workload.yaml on my filesystem and invoke "tanzu apps workload apply -f workload.yaml --update-strategy replace"
Then the apps plugin will return an error because required field is missing from the workload definition("name" ).
```

### Describe alternatives you've considered
1. requiring all removals to be executed via flags (as exists today)
1. create a new sub-command `tanzu apps workload replace`
1. provide a mechanism to persist a configured default

**Comment by scothis** [comment]
I lean towards `--replace`. `--overwrite` is also ok.

`--force` typically means bypassing safety checks/prompts, it doesn't change the semantics of the command.

**Comment by danfein** [comment]
revised deprecation notice to shorten + include the flag as a fallback option

```
WARNING: Configuration file processing is changing. By default, provided configuration files will replace existing configuration rather than being merged. The change will take place after the 1.6 update. “—overwrite=false” can be used to merge configuration.
```

**Comment by heyjcollins** [comment]
Thanks for the feedback @scothis.

After further consideration with @danfein, we've made some substantive changes to this issue and would be interested in your feedback.

The crux of the changes revolve around trying to provide a solution that will make sense in the longer term once we change the default behavior when a user passes `--file workload.yaml` from merge to replace.

Thoughts?

**Comment by scothis** [comment]
You could introduce an `--update-strategy` flag with two valid values `merge` and `replace`. `merge` would be the default today, and once the deprecation period is over, change the default to `replace`. Users can be explicit with their desired semantics to not be affected by the default value change.

**Comment by danfein** [comment]
Proposed help text for new flag 

```
--update-strategy          specify configuration file update strategy (supported strategies: merge, replace[default] )
```

**Comment by heyjcollins** [comment]
## AC
* confirmed deprecation warning message
* confirmed --help 
* confirmed --update-strategy flag not included in `tanzu apps workload create -h` (NICE)
* confirmed explicit `--update-strategy merge` behaves exactly as-if not passing the flag at all
* confirmed `--update-strategy replace` along with passing new values via flags
* confirmed `--update-strategy replace` property/value  (eg env foo: bar) is overwritten by flag `--env foo=replace`
