### ISSUE TITLE
workload create/update/apply supports --export -- to optimize programmatic  workflows

### ISSUE THREAD

**Issue by heyjcollins** [vmware-tanzu/apps-cli-plugin#34]
### Description of problem

adding support for `--export` to  `tanzu apps workload apply` will make the tilt file command simpler/more efficient otherwise devs will have to specify `tanzu apps workload apply`, then `tanzu apps workload get --export.`  Seems a little unwieldy.  

If adding this support to `apply` - we should add it to `workload create` and `workload update` for consistency (so far all the commands have the same flags and we're setting an expectation).

### Proposed solution

When `--export` is passed in with create/update/apply, Expect it to return the workload just created/updated/applied.

```gherkin
Given I have a compliant workload.yaml for my-app
When I create or update my-app workload and include the --export flag (or the --export and --output=yaml/yml flags/values) in my incantation
Then the output  from the command, displayed after confirming the prompt, contains only the content that would be returned if I were to have run "tanzu apps workload get my-app --export"  
```

```gherkin
Given I have a compliant workload.yaml for my-app
When I create or update my-app workload and include the --export and --output=json flags/values in my incantation
Then the output  from the command, displayed after confirming the prompt, contains only the content that would be returned if I were to have run "tanzu apps workload get my-app --export --output json"  
```

```gherkin
Given I have a compliant workload.yaml for my-app
When I create or update my-app workload and include the --export and --output=json flags/values in my incantation
Then the output  from the command, displayed after confirming the prompt, contains only the content that would be returned if I were to have run "tanzu apps workload get my-app --export --output json"  
```

```gherkin
Given I have a compliant workload.yaml for my-app
When I create or update my-app workload and include the --export and --yes and --output=json flags/values in my incantation
Then the output  from the command is displayed without user-prompt and contains only the content that would be returned if I were to have run "tanzu apps workload get my-app --export --output json"
```

```gherkin
Given I have a compliant workload.yaml for my-app
When I create or update my-app workload and include the --export and --yes and --output=json flags/values in my incantation, but some error occurs which prevents the workload object from becoming available within the timeout period (default 10 minutes)
Then then output  from the command is "[]"
```

```gherkin
Given I have a compliant workload.yaml for my-app
When I create or update my-app workload and include the --export and --yes and --output=yaml/yml flags/values in my incantation, but some error occurs which prevents the workload object from becoming available within the timeout period (default 10 minutes)
Then then output  from the command is "---"
```

### Examples

**Current UX:** (--export isn't supported)
```
03/17/22-15:28:59 tanzu % tanzu apps workload create -f app-assets/valid-yaml.yaml
Create workload:
      1 + |---
      2 + |apiVersion: carto.run/v1alpha1
      3 + |kind: Workload
      4 + |metadata:
      5 + |  labels:
      6 + |    app.kubernetes.io/part-of: tanzu-java-web-app
      7 + |    apps.tanzu.vmware.com/has-tests: "true"
      8 + |    apps.tanzu.vmware.com/workload-type: web
      9 + |  name: tanzu-java-web-app-2-6
     10 + |  namespace: default
     11 + |spec:
     12 + |  source:
     13 + |    git:
     14 + |      ref:
     15 + |        branch: spring-boot-2.6
     16 + |      url: https://github.com/odinnordico/tanzu-java-web-app

? Do you want to create this workload? Yes
Created workload "tanzu-java-web-app-2-6"
```

*********************

**Proposed UX** (--export and --yes included)
* if `--yes` hasn't been provided and prompt should be triggered.
* `--output/-o` should support `json` or (`yaml` or `yml`) (default output: `yaml`)
```
03/17/22-15:28:59 tanzu % tanzu apps workload create -f app-assets/valid-yaml.yaml --export --yes
---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    app.kubernetes.io/part-of: tanzu-java-web-app
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
  name: tanzu-java-web-app-2-6
  namespace: default
spec:
  source:
    git:
      ref:
        branch: spring-boot-2.6
      url: https://github.com/odinnordico/tanzu-java-web-app
03/17/22-15:29:13 tanzu %
```

*********************

**Proposed UX** (--export and -o json and --yes included)

```
 03/17/22-15:28:59 tanzu % tanzu apps workload create -f app-assets/valid-yaml.yaml --export -o json
{
  "apiVersion": "carto.run/v1alpha1",
  "kind": "Workload",
  "metadata": {
    "labels": {
      "app.kubernetes.io/part-of": "tanzu-java-web-app",
      "apps.tanzu.vmware.com/has-tests": "true",
      "apps.tanzu.vmware.com/workload-type": "web"
    },
    "name": "tanzu-java-web-app-2-6",
    "namespace": "default"
  },
  "spec": {
    "source": {
      "git": {
        "ref": {
          "branch": "spring-boot-2.6"
        },
        "url": "https://github.com/odinnordico/tanzu-java-web-app"
      }
    }
  }
}
03/17/22-15:29:13 tanzu %
```

### Describe alternatives you've considered
* requiring two commands as is current
* providing --export silently implies --yes

### Additional context/requirements
1. is `--yes` assumed?
   - **Answer:** No. We will not assume yes. Users/scripts will need to provide that.
1. should we support `-o yaml/json` when `--export` is provided?
   - **Answer:** Yes --- default should be `yaml`
1. help output - explanation
   - @danfein can you provide this content?
1. error cases
   - **see gherkin's above**

### open questions:
* need to have a timeout be automatically applied (same as the `--wait-timeout` default value)
  * **but** should we actually generic-ize the timeout flag name to `--timeout`? so it can be used with `--wait` or `--export`

**Comment by heyjcollins** [comment]
comments originally submitted by @paulcwarren

Just FYI, for tilt we require the --export (in general) to be able to return the workload in the cluster. Tilt requires the uid field which is what it then bases its tracking off of.

************************

We would also require the ability to --quiet any other output that isn't the eventual workload yaml.

**Comment by heyjcollins** [comment]
@paulcwarren - do you see any issue with `--export` implying `--yes` and `--quiet`?

**Comment by scothis** [comment]
>Just FYI, for tilt we require the --export (in general) to be able to return the workload in the cluster. Tilt requires the uid field which is what it then bases its tracking off of.

The idea behind `--export` is that is makes take a resource in the cluster and makes it appropriate to write into a gitops store and share. It intentionally strips off the uid and other cluster specific fields. You want something more like `-o yaml` for create/update/apply

**Comment by scothis** [comment]
> do you see any issue with `--export` implying `--yes` and `--quiet`?

I do, `--yes` is an explicit opt-in to not be prompted before potentially destructive actions. Making it implicit weakens its purpose. In the case here of using a script to drive the command, the script can specify the extra flags it cares about. One flag changing the implicit value of an unrelated flag is a good way to surprise users.

**Comment by heyjcollins** [comment]
@scothis - I agree with the sentiment in your previous comment and have updated the issue accordingly.
`--yes` is not implied if a user includes `--export` (users must provide `--yes` to skip prompts).

**Comment by scothis** [comment]
It's worth double checking that the prompts are on stderr so that stdout can be piped to another tool with the exported content.

**Comment by heyjcollins** [comment]
After further clarifying discussions with @paulcwarren and my team, I've decided against implementing this and we'll stick with the 2 command approach which works today.
`apps workload apply...` followed by `apps workload get -o yaml/json` to get the uid.
