### ISSUE TITLE
--sub-path parameter supported for `--local-path` and `--git-*`

### ISSUE THREAD

**Issue by heyjcollins** [vmware-tanzu/apps-cli-plugin#35]
### Description of problem

* Currently there is not a way for someone to specify a sub-section of a repo or a local project directory to create/update their workload from.
* Additionally, if there is a code change anywhere in the repo, any workload that references the repo will be rebuilt, even if there are no changes in the workload code.

#### Original comment from Oded Shopen, TSL:
> Hi. We need a --sub-path parameter for tanzu apps workload create, similar to how it works in TBS.
Many GIT ?repositories contain many sub-modules in the same project, so we need to let the pipeline know which sub-path we want to use for the workload creation.

### Proposed solution

```gherkin
Given I'm currently in the root directory of project in A which includes sub-component dirs B and C
When I run "tanzu apps workload create/update/apply my-app --local path . --sub-path B/
Then the entire contents of my project are uploaded and the workload object includes both spec.source.image=source-image-reference and spec.source.subPath=B
```

If an absolute path is provided for the sub-path value (for either `--git*` or `--local-path`), and the sub-path is legit, the plugin should be able to handle that scenario gracefully (meaning - it should work and not error).

### Open Questions:
* can the sub-path be changed after workload creation?
* can the sub-path be removed after workload creation? 
* can you just pass in sub-path in a workload update/apply (for existing workload - with and/or without previously configured sub-path)
* can/should it be possible to remove --sub-path if previously set? (this question is broader than just sub-path
  * if we decide on a pattern for this, we must apply it to other flags (limit-cpu, limit-memory, request-cpu,  request-memory) 

**Error Cases:**
* `--sub-path` value provided doesn't match a directory under what's provided for --local-path
* `--sub-path` and `local-path` point to same directory
* `--sub-path` value provided without  `--git*` or `--local-path`
* `--sub-path` points to an individual file which isn't a JAR/ZIP (discuss - is a single file sufficient to run a workload?)

**Autocomplete:**
* `--local-path` (to a directory on the filesystem) -- auto-complete sub-directories under the --local-path directory
* `--local-path` (to a JAR/Zip) -- auto-complete to directory structure (discuss implementation complexity/cost)
* `--git*` -- auto-complete sub-directory (discuss implementation complexity/cost)

### Describe alternatives you've considered
* (sub-section problem) Pull code down and deploy the subsection locally
* (rebuilding on changes problem) Could use `--git-sha` to manually specify which commit to build from
* sub-path was legitimate in original workload creation, then in subsequent update/apply, refers to a `--local-path` directory which doesn't include the directory originally set for sub-path -- what happens?
* sub-path no longer exists in gitHub after a commit has been made -- what happens?

### Next Steps:
[ ] Additional feedback on how common it is to have multiple buildable workloads in a single repo to better understand the usecase(s).
[ ] Investigate feasibility of the underlying components (build service, supply chain) and how they might support the described behavior

### Additional context
Issue originally submitted by @danfein

**Comment by heyjcollins** [comment]
Comment originally submitted by @jeffellin:

Seeing this issue with a customer, they keep the code for their .Net Core projects in a subdirectory, We are trying to demo TAP inner loop for them and are unable to do so without manually creating the image. I think it's ok that any code in the repo would trigger a rebuild in this case, we already have this issue with TBS.

**Comment by heyjcollins** [comment]
Thanks Nivedita - I agree with you that it doesn’t only apply to —sub-path and wjatever we do for that case, we’ll make sure the pattern is consistent.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by scothis** [comment]
> **Error Cases:**
> 
> * `--sub-path` value provided doesn't match a directory under what's provided for --local-path
> * `--sub-path` and `local-path` point to same directory
> * `--sub-path` value provided without  `--git*` or `--local-path`
> * `--sub-path` points to an individual file which isn't a JAR/ZIP (discuss - is a single file sufficient to run a workload?)

The only condition that is actually an error that the CLI should enforce is defining a subPath without an otherwise valid `.spec.source`

**Comment by rashedkvm** [comment]
@heyjcollins question, should `--sub-path` in UX support the current directory? 

Example `--local-path ~/project-root-dir/ --sub-path .`

**Comment by scothis** [comment]
> @heyjcollins question, should `--sub-path` in UX support the current directory?
> 
> Example `--local-path ~/project-root-dir/ --sub-path .`

a sub path of `"."` is logically equivalent to the default of `""`
