### ISSUE TITLE
Ability to change between source registry and public registry

### ISSUE THREAD

**Issue by shashwathi** [vmware-tanzu/apps-cli-plugin#365]
### Description of problem

If user has deployed a workload with a registry then wants to update workload to use registry shipped with TAP, its not possible.

### Proposed solution

```gherkin
Given workload is created with public registry
When ser wants to update workload to use local source reigstry
Then workload should be updated to use local source registry
```

**Comment by atmandhol** [comment]
This does not apply anymore as we will be working with a new architecture that does not deploy a source registry on the TAP cluster.
