### ISSUE TITLE
`--no-color` strips all color from `workload tail` output

### ISSUE THREAD

**Issue by heyjcollins** [vmware-tanzu/apps-cli-plugin#368]
### Description of problem

The `--no-color` flag update made in PR #362 covers all scenarios except for some of the `workload tail` output remains colorized despite providing the `--no-color` flag

### Proposed solution

remove all color when `--no-color` is provided.
do not attempt to remove emojis/animations from the logging output.

### Example screenshot

![Screen Shot 2022-10-06 at 1 54 07 PM](https://user-images.githubusercontent.com/37092016/194631398-aba8f975-1e6f-4f47-98b3-dcc56376bfb1.png)

### Additional context
From @odinnordico: 
```stern (tail-lib) uses a different library to color the output, that is why the it needs to be handle different than other parts in the plugin```

From @scothis:
```The color is in the content being tailed. You could strip all ansi control characters```

**Comment by scothis** [comment]
> stern (tail-lib) uses a different library to color the output

This isn't correct. [Stern also uses github.com/fatih/color](https://github.com/vmware-tanzu/apps-cli-plugin/blob/cf9a5c4f3b7f58761c89e64e267090cf62237b5b/vendor/github.com/stern/stern/stern/tail.go#L45-L46).

The apps plugin is correctly disabling the color output that stern adds to the logs. What remains is the actual content of the logs. Be conservative about the modifications you make to content you didn't define and don't control. Stripping color and animations seems safe as the source has no idea if a compatible terminal is viewing the content. Stripping emoji feels wrong unless you are sure you understand the context the emoji was expressed or the original meaning remains accessible.
