### ISSUE TITLE
add `--since 1h --timestamp` to the command tip displayed in `workload create/apply/update/get`

### ISSUE THREAD

**Issue by heyjcollins** [vmware-tanzu/apps-cli-plugin#369]
### Description of problem
In the output from `workload create/apply/get`, we recommend users run `workload tail` to view logs for their workload via a tip at the very end of the command output.

In a troubleshooting scenario, a problem has already occurred, so running the recommended `tail` command isn't likely to return log messages related to that problem.

We've received feedback from users asking how to view logs that were emitted prior to the moment the `workload tail` command is invoked. This indicates users aren't readily discovering that this feature is already supported.
And the fact that we're recommending a `tail` incantation which doesn't improve a user's ability to discover the feature while also not being likely to provide value as-is, is a UX miss.

We've also observed many users tail workload logs and include `--timestamp`.
Additionally, log message timestamps are considered valuable and we should include the flag in our recco.

### Proposed solution

Include `--timestamp --since 1h` in the example command being recommended. 

### Example

Update the command tip from: 
```To see logs:   "tanzu apps workload tail foo"```
To:
```To see logs:   "tanzu apps workload tail foo --timestamp --since 1h"```

### Describe alternatives you've considered
recommend use of `--since` outside of the recommended command: 
```To see logs:   "tanzu apps workload tail foo" (include "--since" to view previous logs)```

**Comment by atmandhol** [comment]
@heyjcollins Should we add `--timestamp` too?

**Comment by heyjcollins** [comment]
@atmandhol - good suggestion. Done!

**Comment by atmandhol** [comment]
Discussed with @heyjcollins and decided to change the help to say 1h.
