### ISSUE TITLE
Workload events command

### ISSUE THREAD

**Issue by danfein** [vmware-tanzu/apps-cli-plugin#399]
### Description of problem

Logs and events are helpful for seeing what is happening on a system, and troubleshooting when things go awry.

Today it is not easy to see events from the different resources associated with building and running a workload.

### Proposed solution

The CLI could bring together the events from the different resources associated with a workload, in the same way we do with `tail` to bring together the logs.

### Example

```
$ tanzu apps workload events <WORKLOAD NAME>

LAST SEEN   TYPE     REASON                         OBJECT                      MESSAGE
20m         Normal   StampedObjectApplied           workload/where-for-dinner   Created object [gitrepositories.source.toolkit.fluxcd.io/where-for-dinner]
20m         Normal   ResourceHealthyStatusChanged   workload/where-for-dinner   [app-config] found healthy status in [<nil>] changed to [True]
20m         Normal   ResourceHealthyStatusChanged   workload/where-for-dinner   [service-bindings] found healthy status in [<nil>] changed to [True]
20m         Normal   ResourceHealthyStatusChanged   workload/where-for-dinner   [api-descriptors] found healthy status in [<nil>] changed to [True]
20m         Normal   StampedObjectApplied           workload/where-for-dinner   Created object [deliverables.carto.run/where-for-dinner]
```

#### Event flag
* considered using `$tanzu apps workload get NAME --events` 
* This would be inconsistant with tail, which is it's own subcommand
* If we want to add additional control to the events command (filtering for example) it would be nice to associate them with the events command rather than adding more flags to the get command.

#### App events
The apps abstraction would benefit from being able to list/get apps, as well as see the aggregated logs and events from a set of associated workloads. 

```
$ tanzu apps events <APP NAME>

LAST SEEN   TYPE     REASON                         OBJECT                      MESSAGE
20m         Normal   StampedObjectApplied           workload/where-for-UI     Created object [gitrepositories.source.toolkit.fluxcd.io/where-for-dinner]
20m         Normal   ResourceHealthyStatusChanged   workload/where-for-data   [app-config] found healthy status in [<nil>] changed to [True]
20m         Normal   ResourceHealthyStatusChanged   workload/where-for-data   [service-bindings] found healthy status in [<nil>] changed to [True]
20m         Normal   ResourceHealthyStatusChanged   workload/where-for-UI  
```

#### Color
Warning event types could be presented in color to make them more discoverable when reviewing long lists

#### Pagination / limit output
The example workloads I saw only had a few events saved, so the lists were short. If it turns out to be common to have very long lists it may be worth exploring a flag to limit the length of the output.

#### Filtering / field-selector
If event lists run long it would be helpful to be able to cherry-pick or filter, for example returning non-normal event types, or events associated with a particular resource.

**Comment by atmandhol** [comment]
The most recent events should be on the top of the output. i.e. order the events in ascending order. This matches the behavior that `kubectl` has.

**Comment by atmandhol** [comment]
The `workload events` command should also include the events associated with the resources that are stamped out by the supply chain and delivery for that workload.

**Comment by heyjcollins** [comment]
Visibility into events will be covered as part of our `application inspector` spike and I'm going to close this issue.
If we pivot away from the apps inspector based on the spike, we can consider reopening this issue for implementation.
