### ISSUE TITLE
Ability to switch registry for an existing workload

### ISSUE THREAD

**Issue by shashwathi** [vmware-tanzu/apps-cli-plugin#429]
### Description of problem

If a workload already exists and user wants to switch from external registry to internal source registry, its not possible today with current design.

### Proposed solution

- Adding a flag to let the user decide which registry to opt into

**Comment by heyjcollins** [comment]
Given we're going to create a local-source proxy which points to an off-cluster registry (rather than provide an on-cluster registry solution as originally planned), this issue isn't something we need to address so I'm going to close it.
