### ISSUE TITLE
Options for opting out of progress bar in the workload apply output

### ISSUE THREAD

**Issue by shaheerkootteeri** [vmware-tanzu/apps-cli-plugin#440]
### Description of problem

Progress bar takes up a lot of space in Visual Studio's output window after the VS extension applies workloads. A way to opt out from displaying progress bar, or update the progress bar library to a different one that displays progress using less space on vs code output terminal.

We need a way to disable it.

### Proposed solution

```gherkin
Given I've run ANY `tanzu apps` subcommand and included `--no-color`
When I review the command output
Then there is no color, bold, emojis, or animations/progress-bar in the output
```

```gherkin
Given I've invoked the creation of a workload via my supported IDE developer extension for TAP (that's been updated to include `--no-color` in the command incantations
When I review the command output in the IDE
Then there is no color, bold, emojis, or animations/progress-bar in the output
```

### To Dos
1. when `--no-color` is provided, progress bar shouldn't be displayed (in addition to color, bold, emojis)
2. update `--no-color` help to include animations
    ```
    --no-color          deactivate color, bold, animations, and emoji output
   ```

### Example
![image](https://user-images.githubusercontent.com/7171846/211050368-37d7f6be-dd13-4fc8-a7b0-8909c163f3f0.png)

### Describe alternatives you've considered
`--no-progress` -- to suppress just the animation progress bar --- decided against this given we're already using `--no-color to suppress more than just color, there's already a large number of flags for `create/apply` and because there's precedence for using `--no-color` to suppress multiple elements needed for scripting/automation.

### Additional context
We'll likely do this as a separate issue after we release `v0.11.0`
Imgpkg uses the progress notifications for copy command , and imgpkg hides the progress bar if the file descriptor is not a terminal. VS code output doesn't display progress bar for imgpkg copy command. Apps CLI can  implements the additional validations on terminal type before displaying the progress bar.

**Comment by atwoosnam** [comment]
Hey I noticed the proposed solution is currently written as:
> Given I've created a workload via vs code extension 
> When I view the vs code output terminal
> Then the progress bar does not display taking up additional space

It may not matter on your end, but just to clarify: the screenshot above is from the [Visual Studio extension](https://github.com/vmware-tanzu/tanzu-developer-tools-for-visual-studio) (not to be confused with extension for VS _Code_). 

The output in that screenshot is piped into Visual Studio from a `tanzu apps wld apply` command, so if it's possible to just avoid printing this progress bar altogether, I don't think it'll be necessary to test in Visual Studio specifically (although if you want to, the .net developer experience team can help with that).

The naïve thought that came to mind when I first asked about an "opt-out" option in Slack was an extra flag e.g. `--no-progress`. Dunno whether or not that's an acceptable solution for you all, but in terms of consumption, that would be really easy for us on the Visual Studio extension team :)

**Comment by heyjcollins** [comment]
We already use `--no-color` to suppress color, bold, and emoji output. 
So after some consideration, we've decided to include suppressing the progress bar (and any other animation in the future) in that.
