### ISSUE TITLE
Bump the version of Tanzu Framework to v0.28.0

### ISSUE THREAD

**Issue by atmandhol** [vmware-tanzu/apps-cli-plugin#448]
### Description of problem

The version of Tanzu Framework currently in use is v0.25.0 and it's outdated.

### Proposed solution

We should upgrade the Tanzu Framework in the CI as well as the go.mod to use the latest v0.28.0.

NOTE: Also update the development.md and README.md with the new version.

**Comment by warango4** [comment]
When trying to update, `tanzu-framework v0.25.4` has an older version of `apimachinery` which we're no longer using so the upgrade crashes against our dependencies. 

We will have to wait until a new release of tanzu-framework that upgrades its dependencies as well. 

> The problem is that` cluster-api-provider-aws` repo as they have it is using `ClusterName` (https://github.com/kubernetes/apimachinery/blob/v0.23.5/pkg/apis/meta/v1/types.go#L276) which is in an older version of `apimachinery` (`v0.23.5`) and we have `v0.25.4`
