### ISSUE TITLE
Use a lazy rest mapper

### ISSUE THREAD

**Issue by scothis** [vmware-tanzu/apps-cli-plugin#466]
### Description of problem

A rest mapper is used to convert Group/Version/Kinds (GVKs) to rest endpoints on the api server. When a process starts up, the rest mapper is populated using the discovery api, making a request for each Group/Version defined in the cluster. In clusters with a lot of apis, this would trigger the client side rate limiter to prevent spamming the api server.

### Proposed solution

There's a new lazy rest mapper introduced upstream by https://github.com/kubernetes-sigs/controller-runtime/issues/1603

This rest mapper should allow us to remove custom rate limit thresholds by making only the essential requests to the api server.

### Describe alternatives you've considered

Our current solution was to increase the client side limit to a threshold the warning is no longer printed. This solved the UX problem of printing a warning to the console in the middle of a command, but it still blocks while the requests are made and results in load on the api server.

### Additional context

Custom rate limiter is applied here:
https://github.com/vmware-tanzu/apps-cli-plugin/blob/61b716a39fa221f3685f393f30d3d4accd37cd2c/pkg/cli-runtime/client.go#L209

**Comment by heyjcollins** [comment]
Thanks for bringing this to our attention Scott. I'll bump this into our backlog.
cc @atmandhol ...
