### ISSUE TITLE
`tanzu apps workload get` doesn't show the workload URL in TCE

### ISSUE THREAD

**Issue by kartiklunkad26** [vmware-tanzu/apps-cli-plugin#58]
### Please fill out the issue checklist below and provide ALL the requested information.

- [ ] I reviewed open and closed Github issues that may be related to my problem.
- [X] I am reporting a bug that others will be able to reproduce.

### Describe the bug
When I install the tanzu apps cli plugin, and use the `tanzu apps workload get` command, I want to see the URL of my deployed workload. But that doesn't happen right now. 

## Expected Behavior

I expect to get the workload URL when I run `tanzu apps workload get`

## Steps to Reproduce the Bug

1. Follow the [App Toolkit Package README](https://tanzucommunityedition.io/docs/v0.11/package-readme-app-toolkit-0.1.0/#usage-example) for installing, configuring and creating Tanzu workload
2. Then run `tanzu apps workload get`, you'll see the below output. 

## Screenshots or additional information and context

```
---
lastTransitionTime: "2022-03-30T18:21:36Z"
message: ""
reason: Ready
status: "True"
type: Ready

Pods
NAME                                     STATUS      RESTARTS   AGE
tanzu-simple-web-app-build-1-build-pod   Succeeded   0          4d19h
tanzu-simple-web-app-build-2-build-pod   Failed      0          47h
```

## Version (Apps plugin version, Version of K8s running on cluster)

Kubernetes version - v1.22.4

tanzu version
```version: v0.11.2
buildDate: 2022-03-24
sha: 6431d1d
```

tanzu apps version - `v0.5.1`

### Environment where the bug was observed (cloud, OS, etc)
TCE v0.11

### Cross-posted TCE Issue

https://github.com/vmware-tanzu/community-edition/issues/3885

**Comment by scothis** [comment]
The CLI is looking for the label `carto.run/workload-name={the-workload-name}` that isn't defined on the Knative Service. Without the label, the CLI has no ability to link together resources created because of the workload from pre-existing resources. https://github.com/vmware-tanzu/community-edition/blob/bea08ceadb86f1b363eba61c67961755cca379e9/addons/packages/app-toolkit/0.1.0/test/example_sc/kpack-templates.yaml#L158

**Comment by kartiklunkad26** [comment]
@scothis Thank you Scott. We will look to update the usage example Supply Chain to use the correct label. I'll close this issue as this isn't a bug with the CLI plug-in itself. 

Thank you for the fast investigation.
