### ISSUE TITLE
ServiceAccountName is removed for apply/update workloads commands unless included in a file

### ISSUE THREAD

**Issue by scothis** [vmware-tanzu/apps-cli-plugin#78]
### Please fill out the issue checklist below and provide ALL the requested information.

- [x] I reviewed open and closed Github issues that may be related to my problem.
- [x] I am reporting a bug that others will be able to reproduce.

### Describe the bug

For a workload with a `.spec.serviceAccountName` set, when executing an apply/update command the service account is unset.

```
tanzu apps workload update petclinic --label hello=world
Update workload:
...
  3,  3   |kind: Workload
  4,  4   |metadata:
  5,  5   |  labels:
  6,  6   |    apps.tanzu.vmware.com/workload-type: web
      7 + |    hello: world
  7,  8   |  name: petclinic
  8,  9   |  namespace: default
  9, 10   |spec:
 10, 11   |  env:
 11, 12   |  - name: SPRING_PROFILES_ACTIVE
 12, 13   |    value: mysql
 13     - |  serviceAccountName: default
 14, 14   |  serviceClaims:
 15, 15   |  - name: db
 16, 16   |    ref:
 17, 17   |      apiVersion: v1
...

? Really update the workload "petclinic"? No
```

### Expected behavior

One should be able to execute an update/apply command against that workload to modify another value without the service account being unset.

### Steps to Reproduce

1. create a workload with a service account name2. 
2. run any `tanzu apps workload apply/update` command that would change the workload and doesn't also include the `--file` flag. 

### Version (Apps plugin version, Version of K8s running on cluster)

Custom build from main HEAD fc7b7180fe43523645976fcb0fb79aaf8b0f95d6

**Comment by heyjcollins** [comment]
## AC
1. updating workload (e.g. adding a param or env var via flag) no longer removes serviceAccountName
2. setting `serviceAccountName: ""` in file still unsets the property in the workload object
3. removing `serviceAccountName` in file still unset the property in the workload object
